### ISSUE TITLE
Python Parser errors after HA 2023.6.0 update (python 3.11)

### ISSUE THREAD

**Issue by Sphericals79** [mampfes/hacs_waste_collection_schedule#1028]
Home Assistant 2023.6.0
Supervisor 2023.06.1
Operating System 10.2
Frontend 20230607.0 - latest

HACS WCS: 1.40.0

After updating Home Assistant to latest version, WCS throws this error for C-Trace calendar:

_Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation) 
First occurred: 7. Juni 2023 um 23:57:59 (2 occurrences) 
Last logged: 01:59:18

```
fetch failed for source C-Trace: 
Traceback (most recent call last): 
File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 340, in parts
validate_token(name) 
File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 128, in validate_token 
raise ValueError(name) ValueError: <!DOCTYPE html>

 During handling of the above exception, another exception occurred:

Traceback (most recent call last): 
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch
entries = self._source.fetch() 
^^^^^^^^^^^^^^^^^^^^ 
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/c_trace_de.py", line 213, in fetch
 dates = self._ics.convert(r.text) 
^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 38, in convert 
events: List[Any] = icalevents.events( 
^^^^^^^^^^^^^^^^^^ 
File "/usr/local/lib/python3.11/site-packages/icalevents/icalevents.py", line 57, in events 
found_events += parse_events( 
^^^^^^^^^^^^^ 
File "/usr/local/lib/python3.11/site-packages/icalevents/icalparser.py", line 288, in parse_events
calendar = Calendar.from_ical(content) 
^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/usr/local/lib/python3.11/site-packages/icalendar/cal.py", line 330, in from_ical
name, params, vals = line.parts() 
^^^^^^^^^^^^ 
File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 352, in parts
raise ValueError( ValueError: Content line could not be parsed into parts: '<!DOCTYPE html>': <!DOCTYPE html>_
```

<reformatted by @5ila5>

**Comment by 5ila5** [comment]
This does not look like an python11 issue the source requests data from the website but it provides some html instead of the ical file. Did your service provider change something on the website. All our Test cases work except the one for WZV they cahnged the ical link from  `https://web.c-trace.de/segebergwzv-abfallkalender/[..]/abfallkalender/cal?[..]` to `https://web.c-trace.de/segebergwzv-abfallkalender/[..]/abfallkalender/cal/2023?[..]` but the acutal file is not located at either path (pdf/excel file work for the old and _new_ path)

**Comment by Sphericals79** [comment]
Thanks for checking. Indeed, checking manually for the latest iCal file, I receive an error:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/117170036/cb0b0275-90e0-4dc7-bb9a-9450472f478f)

Guess have to wait for it to be working again (or using a iCal file locally.
