### ISSUE TITLE
East Riding Yorkshire not working

### ISSUE THREAD

**Issue by pops106** [mampfes/hacs_waste_collection_schedule#1165]
Hello, I have just set this up and unfortunatley it looks like it is failing to connect to East Riding Yorkshire or I have managed to do something wrong.

I have tried the YAML in a couple of different ways;

`waste_collection_schedule:
    sources:
      - name: eastriding_gov_uk
        args:
          postcode: "POST CODE"
          uprn: "UPRN"`

and

`waste_collection_schedule:
    sources:
    name: eastriding_gov_uk
    args:
      postcode: "POST CODE"
      uprn: "UPRN"`

and

`waste_collection_schedule:
    sources:
    name: eastriding_gov_uk
    args:
      postcode: POSTCODE
      uprn: UPRN`

`Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 14:17:55 (1 occurrences)
Last logged: 14:17:55

fetch failed for source East Riding of Yorkshire Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/eastriding_gov_uk.py", line 37, in fetch api_key = re.findall(REGEX["API_KEY"], r1.text)[0] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^ IndexError: list index out of range`

I don't really know what I am doing but if this helps...

In your code it says;

`# get api_key and licensee
        r1 = s.get("https://www.eastriding.gov.uk/environment/bins-rubbish-recycling/bins-and-collections/bin-collection-dates/")
        api_key = re.findall(REGEX["API_KEY"], r1.text)[0]
        licensee = re.findall(REGEX["LICENSEE"], r1.text)[0]`

When I do MITM Proxy and go to the site I get this;

`GET https://wasterecyclingapi.eastriding.gov.uk/api/RecyclingData/CollectionsData?APIKey=ekBWR8tSiv6qwMo31REEeTZ5FAiMNB&Licensee=BinCollectionWebTeam&Postcode=mypostcode HTTP/1.1`

Is it possibly just the API_KEY vs the APIKey

**Comment by pops106** [comment]
I have just tried filling in the URL manually in a browser

https://wasterecyclingapi.eastriding.gov.uk/api/RecyclingData/CollectionsData?APIKey=ekBWR8tSiv6qwMo31REEeTZ5FAiMNB&Licensee=BinCollectionWebTeam&Postcode=mypostcode

That does appear to work and gives me information for all the addresses in the street

**Comment by dt215git** [comment]
This seems to be the same issue as #1115, and a fix was merged a few weeks ago.
Your options are given in [this response](https://github.com/mampfes/hacs_waste_collection_schedule/issues/1115#issuecomment-1656674656) in that thread.
