### ISSUE TITLE
Not working with 2023.8.4

### ISSUE THREAD

**Issue by EpicLPer** [mampfes/hacs_waste_collection_schedule#1187]
Heya,

after upgrading to 2023.8.4 I'm getting the following errors in system logs and no calendar is being provided.

Home Assistant 2023.8.4  
Supervisor 2023.08.1  
Operating System 10.5  

```
  - Error adding entities for domain sensor with platform waste_collection_schedule
  - Error while setting up waste_collection_schedule platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 750, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/waste_collection_schedule/sensor.py", line 141, in async_added_to_hass
    self._update_sensor()
  File "/config/custom_components/waste_collection_schedule/sensor.py", line 200, in _update_sensor
    upcoming1 = self._aggregator.get_upcoming_group_by_day(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/collection_aggregator.py", line 65, in get_upcoming_group_by_day
    self._entries,
    ^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/collection_aggregator.py", line 17, in _entries
    return [e for s in self._shells for e in s._entries]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/collection_aggregator.py", line 17, in <listcomp>
    return [e for s in self._shells for e in s._entries]
                                             ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_entries'
```
```
Error while setting up waste_collection_schedule platform for calendar

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/waste_collection_schedule/calendar.py", line 31, in async_setup_platform
    dedicated_calendar_types = shell.get_dedicated_calendar_types()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_dedicated_calendar_types'

```
```
Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 212, in _fetch
    shell.fetch()
    ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'fetch'
```
```
source not found: scheibbs_umweltverbaende_at
```

Or maybe something in my setup is wrong? Tho on 2023.8.2 it still worked fine.

Thanks already!

**Comment by EpicLPer** [comment]
Hm, I downloaded the latest "master" version via HACS and now it seems to work. Not sure if the above is still relevant but I'll leave it open for now.

**Comment by EpicLPer** [comment]
Actually, now the entity doesn't show up anymore.
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/8442196/db570a96-c896-4caa-8e88-facf880d92ef)

**Comment by cptwajo** [comment]
@EpicLPer I have still the same error and couldn't easily find the renamed entities (in my huge catalog). Did you do something actively to restore it?
Thanks :)

**Comment by cptwajo** [comment]
Thanks! For me the result looked the same, but the entities were gone completely due to the wrong configuration.yaml settings

**Comment by gomble** [comment]
hello i have the same problem. It seems not to be renamed. I have only one entity and this one is gone.

**Comment by gomble** [comment]
lol with Release 2023.9.1 it is working again
