### ISSUE TITLE
Integration failed after update to 1.42.0

### ISSUE THREAD

**Issue by jezzaaa** [mampfes/hacs_waste_collection_schedule#1259]
I just updated HA and then a few HACS integrations. One of them was the Waste Collection Schedule, upgraded from 1.41.0 to 1.42.0. The logs:

```
2023-09-12 18:08:08.513 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=update>
2023-09-12 18:08:08.525 ERROR (MainThread) [homeassistant.config] Platform error: sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 919, in async_process_component_config
    platform = p_integration.get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 838, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 855, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 21, in <module>
    from waste_collection_schedule import Customize, SourceShell  # type: ignore # isort:skip # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/__init__.py", line 3, in <module>
    from .source_shell import Customize, SourceShell  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'waste_collection_schedule.source_shell'
```

Is there something I did wrong?

**Comment by 5ila5** [comment]
I can't reproduce this behaviour. We did not modify any files mentioned in the error from version 1.41.0 to 1.42.0.

Have your tried reinstalling this integration?

**Comment by jezzaaa** [comment]
Wow. Yes, that's fixed it. Thanks!

**Comment by jezzaaa** [comment]
closed

**Comment by jezzaaa** [comment]
Wow. Yes, that's fixed it. Thanks!
