### ISSUE TITLE
scraper not working after removing asId

### ISSUE THREAD

**Issue by d4nSource** [mampfes/hacs_waste_collection_schedule#126]
Hello,

it seems the scaper.py is still expecting an asId as an argument:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 103, in async_setup
    api.add_scraper(
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 182, in add_scraper
    Scraper.create(
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", line 227, in create
    source = source_module.Source(**source_args)  # type: ignore
TypeError: __init__() missing 1 required positional argument: 'asId'

**Comment by d4nSource** [comment]
I forgot to mention, I'm talking about the 'Stadtreinigung Hamburg' source. wasn't clear from the error message,

**Comment by mampfes** [comment]
Sorry, the documentation was ahead of the release.

Please see version 1.14.0.
