### ISSUE TITLE
not working with citieapps

### ISSUE THREAD

**Issue by thefox69** [mampfes/hacs_waste_collection_schedule#1261]
since  ~ one week the integration stopped working.
- Home Assistant 2023.9.2
- Supervisor 2023.08.3
- Operating System 10.5
- Waste Coll. Rel: 1.42.0 (also tested with 1.41.0)

my config:
```
waste_collection_schedule:
    sources:
    - name: citiesapps_com
      args:
        city: Stockerau
        calendar: Abfallkalender - Abfuhrzone D 
```
tried it already with the example configs, but same error:

```
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 17:39:40 (1 occurrences)
Last logged: 17:39:40

fetch failed for source App CITIES: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, 
in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/citiesapps_com.py", line 53, 
in fetch cities_apps = CitiesApps() ^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/CitiesAppsCom.py", line 780, 
in __init__ r.raise_for_status() File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, 
in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 418 Client Error: I'm a Teapot for url: https://api.citiesapps.com/auth/guest
```

Not really sure  what the reason is, also the http error 418...
thanks in advance

**Comment by 5ila5** [comment]
fix will be part of release 1.43.0 or is available now as master (git) version
