### ISSUE TITLE
Adding Bonn Orange

### ISSUE THREAD

**Issue by morzan1001** [mampfes/hacs_waste_collection_schedule#1309]
Hi, 

today I played around with this HomeAssistant integration and tried to add the appointments from Bonn Orange (https://www.bonnorange.de/service/privatpersonen/abfuhrtermine/termine). Bonn Orange offers an ICS download on their website and an app powered by "AbfallPlus". 

I decided to try to pull data from the app, as that seemed easier than parsing the ICS correctly. I was able to use a proxy to pull the necessary information about waste types, street and municipality from the app, but no API key. The app uses a cookie for authentication. However, the cookie contained an MD5 hash (with a few other things) and I just tried to use this hash as a key. 

Unfortunately, I now get the following errors in the Homeassistant: 
```
Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch
    entries = self._source.fetch()
              ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/abfall_io.py", line 170, in fetch
    dates = self._ics.convert(ics_file)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 38, in convert
    events: List[Any] = icalevents.events(
                        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/icalevents/icalevents.py", line 57, in events
    found_events += parse_events(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/icalevents/icalparser.py", line 286, in parse_events
    raise ValueError("Content is invalid!")
ValueError: Content is invalid!
```

I assume that this is because my key is not correct and the API does not respond with an ICS file or that something else is wrong with the response. Unfortunately I have not found a way to debug this a bit more precisely. Do any of you have a tip for me on how to check the API's response or if my way to get the data from the app (cookie vs. key) works at all? 

Thanks a lot :)

**Comment by 5ila5** [comment]
The website is Athos based and therefore pretty similar to other source we already implemented (abfallwirtschaft_pforzheim_de, awb_emsland_de, bielefed_de, bmv_at, meinawb_de, regioentsorgung_de, rh_etsorgung_de, rv_de, vielefeld_de). The apps are using a different API than the abfallplus source. I started writing an integration for all the abfallplus apps (https://github.com/5ila5/hacs_waste_collection_schedule/tree/add_service_appabfallplusde) but it's not yet completely finished and tested (did not worked on this for some weeks)
