### ISSUE TITLE
Problem with "App Cities" -  after Web Service update

### ISSUE THREAD

**Issue by thefox69** [mampfes/hacs_waste_collection_schedule#1310]
Already working with the **master branch** the wast collection stopped working.
Home Assistant 2023.10.1 
Supervisor 2023.10.0 
Operating System 10.5 
Frontend 20231005.0 - latest 

Seems different from the last Cities Problem, look like these target is a little bit challenging

**Update Issue :**
After an Update on the web service from App Cities it got an errormessage like in #1261.

new Error message
`fetch failed for source App CITIES: Traceback (most recent call last): 
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ 
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/citiesapps_com.py", line 53, in fetch cities_apps = CitiesApps() ^^^^^^^^^^^^ 
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/CitiesAppsCom.py", line 780, in __init__ r.raise_for_status() 
File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.
HTTPError: 418 Client Error: I'm a Teapot for url: https://api.citiesapps.com/auth/guest `

Thanks in advance

**Comment by 5ila5** [comment]
looks like the app is down for maintenance or something

When opening the APP:
![grafik](https://github.com/mampfes/hacs_waste_collection_schedule/assets/38183212/b66f2f6f-3524-4493-a9a8-311d3f868d80)

**Comment by 5ila5** [comment]
for me all test cases work again. You may not have any results yet because the source fetches at around 1 AM where servers were probably still offline. (restart Homeassistant or wait till tomorrow)
