### ISSUE TITLE
Bug: JSON parsing error when getting streets for AppAbfallplusDe

### ISSUE THREAD

**Issue by jbgerth** [mampfes/hacs_waste_collection_schedule#1325]
Version: Commit hash [dc1dc50](https://github.com/mampfes/hacs_waste_collection_schedule/commit/dc1dc501b739efd304c53adb281e47900eaa9bf2)
HA version: 2023.8.2

### Bug Description

I have found a bug when reading the streets from the AppAbfallplusDe service. I am trying to set the street for "[Kreis Cuxhaven](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/app_abfallplus_de.md) / Abfall+ App: abfallappcux" in the city "Wurster Nordseeküste". While retrieving all the streets for the area, the code throws the following error:

```txt
Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 273, in extract_onclicks
    to_return.append(json.loads(string))
                     ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 11 (char 10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/wizard/app_abfallplus_de.py", line 175, in <module>
    main()
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/wizard/app_abfallplus_de.py", line 154, in main
    street = select_street(app, bund_select)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/wizard/app_abfallplus_de.py", line 92, in select_street
    streets = app.get_streets(inquirer.prompt(questions)["street_search"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 491, in get_streets
    for a in extract_onclicks(r):
             ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 275, in extract_onclicks
    raise Exception(f"Failed to parse '{string}', onclick: '{onclick}'")
Exception: Failed to parse '["3660|0|"Campingplatz ""Am Wremer Tief"""",""Campingplatz ""Am Wremer Tief"""","strasse","hnr","",{}]', onclick: 'awk_standort_auswahl_step_fertig('3660|0|"Campingplatz ""Am Wremer Tief"""','"Campingplatz ""Am Wremer Tief"""','strasse','hnr','',{})'
```

### Replication

I've tested this with the [wizard](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py) to generate the config and from Home Assistant. In both cases, the error is thrown.

Here is a YAML to test with the first valid street to not dox myself :wink: :  

```yaml
waste_collection_schedule:
    sources:
    - name: app_abfallplus_de
      args:
        app_id: de.k4systems.abfallappcux
        city: Wurster Nordseeküste
        strasse: Aakweg
        hnr: Alle Hausnummern
```

### Possible fix:

The issue seems to be in this line:
<https://github.com/mampfes/hacs_waste_collection_schedule/blob/dc1dc501b739efd304c53adb281e47900eaa9bf2/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py#L275>

Ideally, the string parsing is improved to cover this edge case. As a quick and dirty local fix, I replaced the error with a `continue` statement, because I don't need this street to work.

**Comment by 5ila5** [comment]
I Improved the parsing to now escape `"` correctly before parsing this fixes the Error for your test case and all existing ones still run as expected.

fixed by #1326
