### ISSUE TITLE
SSL Error after restarting HA

### ISSUE THREAD

**Issue by zimbo86** [mampfes/hacs_waste_collection_schedule#1329]
After restarting my HA instance i cant fetch data anymore:

`This error originated from a custom integration.

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 8:07:25 AM (1 occurrences)
Last logged: 8:07:25 AM

fetch failed for source Abfallwirtschaft Neckar-Odenwald-Kreis: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen httplib_response = self._make_request( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request self._validate_conn(conn) File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn conn.connect() File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect self.sock = ssl_wrap_socket( File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket ssl_sock = _ssl_wrap_socket_impl( File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl return ssl_context.wrap_socket(sock, server_hostname=server_hostname) File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket return self.sslsocket_class._create( File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create self.do_handshake() File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake self._sslobj.do_handshake() ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send resp = conn.urlopen( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen retries = retries.increment( File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='athos.awn-online.de', port=443): Max retries exceeded with url: /WasteManagementNeckarOdenwald/WasteManagementServlet?SubmitAction=wasteDisposalServices&InFrameMode=TRUE (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/awn_de.py", line 64, in fetch r = session.get( File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get return self.request("GET", url, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send raise SSLError(e, request=request) requests.exceptions.SSLError: HTTPSConnectionPool(host='athos.awn-online.de', port=443): Max retries exceeded with url: /WasteManagementNeckarOdenwald/WasteManagementServlet?SubmitAction=wasteDisposalServices&InFrameMode=TRUE (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))`

Using this yaml:

> waste_collection_schedule:
>   sources:
>     - name: awn_de
>       args:
>         city: "xx"
>         street: "xx"
>         house_number: 11
>       customize:
>         - type: Verpackungstonne
>           alias: Gelber Sack
>         - type: Bioenergietonne
>           alias: Biotonne
>         - type: Altpapier, Buendelsammlung
>           alias: Altpapier
> 

I cant add "verify_ssl: false", it is not supported.
any help is much appreciated

**Comment by zimbo86** [comment]
.. in the meantime I downloaded an ics manually and changed my configuration.yaml to ics..

>     - name: ics
>       args: 
>         file: "www/muell2023.ics"
>         verify_ssl: false
