### ISSUE TITLE
Can't configure source without arguments

### ISSUE THREAD

**Issue by AghilasMessara** [mampfes/hacs_waste_collection_schedule#1351]
Hello Team,
I'm trying to configure into HomeAssistant the source that I added Mamirolle info, but I have argument issues.

`args` is marked `required`, so if none is passed, the configuration is invalid.

```
Invalid config for [waste_collection_schedule]: required key not provided @ data['waste_collection_schedule']['sources'][0]['args']. Got None. (See /config/configuration.yaml, line 27). 
```

If a dummy argument is passed. The configuration is valid but the source setup fails.
```
Error during setup of component waste_collection_schedule

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 109, in async_setup
    api.add_source_shell(
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 202, in add_source_shell
    SourceShell.create(
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 196, in create
    source = source_module.Source(**source_args)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Source() takes no arguments
```
I understand that we want the configuration to fail early but the real error will still be seen only when the source is actually instantiated. Because of that I think the arguments shouldn't be required.

What do you think about this?

**Comment by dt215git** [comment]
A quick fix would be to add an arg that isn't used.

```python
class Source:

    def __init__(self, _ = None):
        self._ = None

    def fetch(self):
       ... rest of the code ...
```
```bash
Testing source mamirolle_info ...
  found 2 entries for TestSource
    2024-10-03 : Poubelle grise [mdi:trash-can]
    2024-09-26 : Poubelle jaune [mdi:recycle]
```

**Comment by AghilasMessara** [comment]
I thought of that too because I think it's important to have the arguments as required in most of the sources.
I can make a PR for that
