### ISSUE TITLE
[Bug]: May

### ISSUE THREAD

**Issue by dunkelheim** [mampfes/hacs_waste_collection_schedule#1386]
### I Have A Problem With:

A specific source

### What's Your Problem

Hi,

my city ist Hassel (Weser). I typed it without characters, without the second part compledly, every time the log told me, that the city is unknown.
Now, I typed the city as written above, and got the failure log down below.

I don't know there is somethink missing, or it is a bug, because I am not that deep into that code.
Hope it's right here and thanks for the help.

To the checklist from down below. After Redownloading the "normal" and the "beta", nothing changed. There was no "master" for me, but maybe I just don't understand the meaning of "(master)" in this one.

### Logs

```Shell
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 09:12:55 (1 occurrences)
Last logged: 09:12:55

fetch failed for source Apps by Abfall+: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py", line 109, in fetch for d in self._app.generate_calendar(): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 683, in generate_calendar self.select_hnr() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 554, in select_hnr if compare(hnr["name"], self._hnr_search, remove_space=True): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 286, in compare b = b.replace(" ", "") ^^^^^^^^^ AttributeError: 'int' object has no attribute 'replace'
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by CyberGecko** [comment]
I had the same problem. My solution was to change the value of the **hnr** property from integer to string.
configuration.yaml (not working):
```yaml 
city: CITY
strasse: STREET
hnr: 1
```
configuration.yaml (working):
```yaml 
city: CITY
strasse: STREET
hnr: "1"
```

**Comment by dunkelheim** [comment]
Thank you very much, that solved my problem. Works fine now. =)
Sorry for not testing another city nearby - was to stuck yesterday to figure out this as a test to find out the spacial caracters can't be the problem... =(

**Comment by dunkelheim** [comment]
Thank you very much, that solved my problem. Works fine now. =)
Sorry for not testing another city nearby - was to stuck yesterday to figure out this as a test to find out the spacial caracters can't be the problem... =(
