### ISSUE TITLE
[Bug]: Städteservice Raunheim Rüsselsheim / staedteservice.de

### ISSUE THREAD

**Issue by GUIS2023** [mampfes/hacs_waste_collection_schedule#1400]
### I Have A Problem With:

A specific source

### What's Your Problem

Wont work anymore --NEW Sitestructure 

### Logs

```Shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 340, in parts
    validate_token(name)
  File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 128, in validate_token
    raise ValueError(name)
ValueError: <!doctype html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch
    entries = self._source.fetch()
              ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/staedteservice_de.py", line 42, in fetch
    dates = self.get_dates(session, year, month)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/staedteservice_de.py", line 53, in get_dates
    dates = self._ics.convert(calendar)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 38, in convert
    events: List[Any] = icalevents.events(
                        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/icalevents/icalevents.py", line 57, in events
    found_events += parse_events(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/icalevents/icalparser.py", line 288, in parse_events
    calendar = Calendar.from_ical(content)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/icalendar/cal.py", line 330, in from_ical
    name, params, vals = line.parts()
                         ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 352, in parts
    raise ValueError(
ValueError: Content line could not be parsed into parts: '<!doctype html>': <!doctype html>
```

### Relevant Configuration

```YAML
############ waste_collection #####################
waste_collection_schedule:
  sources:
    - name: staedteservice_de
      args:
        city: "Rüsselsheim"
        street_number: "47"
      customize:
        - type: Schadstoffmobil
          alias: Schadstoffmobil
          picture: '/local/img/icon_trash_grey.png'
        - type: Gelbe Tonne
          alias: GelbeTonne
          picture: "/local/img/icon_trash_green.png"
          use_dedicated_calendar: False
          dedicated_calendar_title: None
        - type: 'Biomüll, Restmüll'
          alias: Biomüll_Restmüll
          picture: "/local/img/icon_trash_blue.png"
          use_dedicated_calendar: False
          dedicated_calendar_title: None
        - type: 'Biomüll, Papiermüll'
          alias: Biomüll_Papiermüll
          picture: '/local/img/icon_trash_grey.png'
          use_dedicated_calendar: False
          dedicated_calendar_title: None
  fetch_time: "20:00"
  day_switch_time: "10:00"
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Fixed, Fix will be part of release 1.44.0 or is available now as master (git) version (HACS: 3-dot menu -> redownload -> change version to `master`)

your old config might still work but some addresses (one of our test case) seemed to not work anymore. Then try providing the street_name and house_number argument ([see documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/staedteservice_de.md))
