### ISSUE TITLE
[Bug]: Source "tbv_velbert_de" is not included in the installation package 

### ISSUE THREAD

**Issue by pille89** [mampfes/hacs_waste_collection_schedule#1441]
### I Have A Problem With:

A specific source, Sensor configuration, The integration in general

### What's Your Problem

Hello, 
in version 1.43.0 the source "tbv_velbert_en" is not included. 
I have manually added the file to the directory: "/homeassistant/custom_components/waste_collection_schedule/waste_collection_schedule/source".

### Source (if relevant)

tbv_velbert_de

### Logs

```Shell
Logger: homeassistant.setup
Source: setup.py:288
First occurred: 12:29:37 (1 occurrences)
Last logged: 12:29:37

Error during setup of component waste_collection_schedule
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 109, in async_setup
    api.add_source_shell(
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 202, in add_source_shell
    SourceShell.create(
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 196, in create
    source = source_module.Source(**source_args)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Source.__init__() got an unexpected keyword argument 'strasse'

-----------------------------------------------------------------------------------------------------

Logger: homeassistant.setup
Source: setup.py:359
First occurred: 12:29:39 (4 occurrences)
Last logged: 12:29:39

Unable to prepare setup for platform waste_collection_schedule.sensor: Unable to set up component.
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: tbv_velbert_de
      args:
        strasse: "Am Lindenkamp 33"
      customize:
        - type: Restmüll-Gefäß
          alias: rest
          icon: mdi:trash-can
        - type: Gelbe Tonne
          alias: gelbersack
          icon: mdi:recycle
        - type: Bio-Tonne
          alias: bio
          icon: mdi:trash-can
  fetch_time: "04:00"
  day_switch_time: "10:00"
      
sensor:
  - platform: waste_collection_schedule
    name: AbfallRestmuell
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - rest

  - platform: waste_collection_schedule
    name: AbfallGelberSack
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - gelbersack

  - platform: waste_collection_schedule
    name: AbfallBio
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - bio

  - platform: waste_collection_schedule
    name: AbfallNaechster
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
the Example config is wrong it should be `street` not `strasse` as the "Configuration via configuration.yaml section" says

**Comment by pille89** [comment]
Thanks, it works today, it really was on the road thank you very much 😋
