### ISSUE TITLE
[Feature]: Enable "bezrik" or "bezirk_id" for AppAbfall+

### ISSUE THREAD

**Issue by MrIcemanLE** [mampfes/hacs_waste_collection_schedule#1445]
### I propose a feature for:

Sources, The integration in general

### Describe your wanted feature

Please add/enable the support of defining a "bezirk" (district) in the source Abfall+ because in my case the de.k4systems.leipziglk doesn't finds my street in the city. Sniffed in the POST request of the website and found that they are using the "bezirk" property

```
f_id_kommune: 2***
f_posts_json[]: a:2:{s:32:"dee3d6ba35a4604e0a5983864c2a7988";s:32:"af255189da613fb013a3a788a743aa63";s:12:"f_id_kommune";s:4:"2***";}
f_id_bezirk: 3**
f_posts_json[]: a:4:{s:32:"dee3d6ba35a4604e0a5983864c2a7988";s:32:"af255189da613fb013a3a788a743aa63";s:12:"f_id_kommune";s:4:"2***";s:12:"f_posts_json";a:0:{}s:11:"f_id_bezirk";s:3:"3**";}
f_id_strasse: 7**
f_posts_json[]: a:5:{s:32:"dee3d6ba35a4604e0a5983864c2a7988";s:32:"af255189da613fb013a3a788a743aa63";s:12:"f_id_kommune";s:4:"2***";s:12:"f_posts_json";a:1:{i:0;s:117:"a:2:{s:32:"dee3d6ba35a4604e0a5983864c2a7988";s:32:"af255189da613fb013a3a788a743aa63";s:12:"f_id_kommune";s:4:"2***";}";}s:11:"f_id_bezirk";s:3:"358";s:12:"f_id_strasse";s:3:"7**";}
f_id_strasse_hnr: 1***
```

**Comment by 5ila5** [comment]
The abfallplus websites use a diffretn API than the apps
the website API is supported by the  [Abfall.IO / AbfallPlus](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfall_io.md) / abfallplus.de source.

For the app API: id_bezirk is set when  selecting a street.
Is your street available when using the App? ([google play stroe](https://play.google.com/store/apps/details?id=de.k4systems.leipziglk))

**Comment by MrIcemanLE** [comment]
The Problem is, that if I enter the "main" city the street isn't found. I understand that the website works in another way. But when I select the main city and no district I get only the streets from the main city. After selecting the district I can only chose "all Streets". So I'm suspecting that the provider has added the districts and inside the small districts only a dummy street "all Streets"

So if I choose `alle Straßen` as a Street a get some Result but for the wrong district because the dummy `alle Straßen` exists in more than one district. In other words: For my city there are the streets from the capital and `n`-times "alle Straßen" where `n` is the number of districts

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 10:18:24 (1 occurrences)
Last logged: 10:18:24

fetch failed for source Apps by Abfall+: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py", line 111, in fetch for d in self._app.generate_calendar(): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 681, in generate_calendar self.select_street() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 519, in select_street raise Exception(f"Street {self._strasse_search} not found.") Exception: Street B *** Weg not found.
```

**Comment by dirtyharryiv** [comment]
I have the exact same problem as @MrIcemanLE
