### ISSUE TITLE
[Bug]: hausmuell_info

### ISSUE THREAD

**Issue by fab242** [mampfes/hacs_waste_collection_schedule#1491]
### I Have A Problem With:

The integration in general

### What's Your Problem

No data is loaded. I think it can't find my address. 

![Issue](https://github.com/mampfes/hacs_waste_collection_schedule/assets/5084385/c4785cc1-8907-498b-acc7-fc5fcfa3483c)

### Logs

```Shell
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 18:38:58 (1 occurrences)
Last logged: 18:38:58

fetch failed for source hausmüll.info: Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 340, in parts validate_token(name) File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 128, in validate_token raise ValueError(name) ValueError: <link href='../pdf/css/kalender.css' rel='stylesheet' type='text/css' media='all'/><div id = 'info'style='width During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/hausmuell_info.py", line 355, in fetch dates = self._ics.convert(r.text) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, in convert events: List[Any] = icalevents.events( ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( ^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalevents/icalparser.py", line 288, in parse_events calendar = Calendar.from_ical(content) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalendar/cal.py", line 330, in from_ical name, params, vals = line.parts() ^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 352, in parts raise ValueError( ValueError: Content line could not be parsed into parts: '<link href='../pdf/css/kalender.css' rel='stylesheet' type='text/css' media='all'/><div id = 'info'style='width:500px;'> <h2 class = 'entsorgerfarbe_txt' style = 'font-zize: 10px;'> Achtung! </h2> <p> Bitte geben Sie die Stra&szlig;e und Hausnummer korrekt an. </p></div>': <link href='../pdf/css/kalender.css' rel='stylesheet' type='text/css' media='all'/><div id = 'info'style='width
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by panteLx** [comment]
Fixed in my PR but every user who uses hausmuell_info needs to update their subdomain (now domain) in order to get a working integration.
Maybe its a better solution to create a new source for erfurt because they're the only one who uses a different domain.

**Comment by 5ila5** [comment]
fixed by #1497

fix will be part of release 1.45.0 or is available now as master (git) version (HACS: 3-dot menu -> re-download -> change version to master)

**Comment by fab242** [comment]
Hi,

Unfortunately I had to reinstall the integration. If I now install the master as described, it doesn't work again. Before the re-installation it worked...

**Comment by fab242** [comment]
@5ila5 

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 09:36:10 (1 occurrences)
Last logged: 09:36:10

fetch failed for source hausmüll.info: Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 340, in parts validate_token(name) File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 128, in validate_token raise ValueError(name) ValueError: <link href='../pdf/css/kalender.css' rel='stylesheet' type='text/css' media='all'/><div id = 'info'style='width During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/hausmuell_info.py", line 355, in fetch dates = self._ics.convert(r.text) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, in convert events: List[Any] = icalevents.events( ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( ^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalevents/icalparser.py", line 288, in parse_events calendar = Calendar.from_ical(content) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalendar/cal.py", line 330, in from_ical name, params, vals = line.parts() ^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 352, in parts raise ValueError( ValueError: Content line could not be parsed into parts: '<link href='../pdf/css/kalender.css' rel='stylesheet' type='text/css' media='all'/><div id = 'info'style='width:500px;'> <h2 class = 'entsorgerfarbe_txt' style = 'font-zize: 10px;'> Achtung! </h2> <p> Bitte geben Sie die Stra&szlig;e und Hausnummer korrekt an. </p></div>': <link href='../pdf/css/kalender.css' rel='stylesheet' type='text/css' media='all'/><div id = 'info'style='width




I had mistakenly installed the new version 1.44.0 in the meantime and then wanted to go back to the master, as described above...


Thx
Fabian

**Comment by 5ila5** [comment]
> line 355, in fetch dates = self._ics.convert(r.text)
This means this is not the master version but the old one as this line moved to line 358. Maybe try redownloading the master version and fully restart HA
