### ISSUE TITLE
[Bug]: Germany: muellmax RSAG gets no ics file, missing last step, missing args in the request

### ISSUE THREAD

**Issue by IamNeo1** [mampfes/hacs_waste_collection_schedule#1498]
### I Have A Problem With:

The integration in general

### What's Your Problem

The provider Müllmax.de with the service RASG "Rsa" has added another step to create an ICS calendar. After selecting your address, you now also have to select the types of waste collection. If you do not request the ICS file without selection. Triggering the submit without selection throws a validation error on the web pages. 
HA throws a parser error with the current config, because the parser expects an ICS and probably receives a web page or nothing at all.
The entity shows status OFF and the calender is empty.

Müllmax RSAG: https://www.muellmax.de/abfallkalender/rsa/res/RsaStart.php

The multiple selection of garbage types must therefore be added to the wizard. All arguments with `mm_frm_fra_` must also be included in the request  in a further step. 

When analyzing the request with all types selected, you see the following arguments in the payload:

- mm_ses: XXX
- xxx: 1
- mm_frm_type: termine
- mm_frm_fra_RM2T: RM2T       "Schwarze Restmülltonne beschriftet mit 2Restmülltonne 2-wö."
- mm_frm_fra_RM4T: RM4T       "Schwarze Restmülltonne beschriftet mit 4Restmülltonne 4-wö."
- mm_frm_fra_BIO1T: BIO1T     "Schwarze Biotonne, Deckel braun, beschriftet mit 1Biotonne Regelabfuhr"
- mm_frm_fra_BIOT: BIOT       "Schwarze Biotonne, Deckel braun, beschriftet mit 2Biotonne 2-wö."
- mm_frm_fra_PAT: PAT         "Schwarze Papiertonne, Deckel grünPapiertonne 4-wö."
- mm_frm_fra_WET: WET         "Schwarze Wertstofftonne, Deckel gelb und gelber SackWertstofftonne oder -sack 4-wö."
- mm_frm_fra_CHR: CHR         "WeihnachtsbaumWeihnachtsbaumabfuhr"
- mm_frm_fra_RM1B: RM1B       "Schwarzer Restmüll-Großbehälter beschriftet mit 1Restmüll-Großbehälter (wö.) für Wohnanlagen"
- mm_frm_fra_RM2B: RM2B       "Schwarzer Restmüll-Großbehälter beschriftet mit 2Restmüll-Großbehälter (2-wö.) für Wohnanlagen"
- mm_frm_fra_RM4B: RM4B       "Schwarzer Restmüll-Großbehälter beschriftet mit 4Restmüll-Großbehälter (4-wö.) für Wohnanlagen"
- mm_frm_fra_PA2B: PA2B       "Schwarzer Papier-Großbehälter, Deckel grün, beschriftet mit 2Papier-Großbehälter (2-wö.) für Wohnanlagen"
- mm_frm_fra_PA4B: PA4B       "Schwarzer Papier-Großbehälter, Deckel grün, beschriftet mit 4Papier-Großbehälter (4-wö.) für Wohnanlagen"
- mm_frm_fra_BIO1B: BIO1B     "Schwarzer Bio-Großbehälter, Deckel braun, beschriftet mit 1Bio-Großbehälter Regelabfuhr für Wohnanlagen"
- mm_frm_fra_BIOB: BIOB       "Schwarzer Bio-Großbehälter, Deckel braun, beschriftet mit 2Bio-Großbehälter (2-wö.) für Wohnanlagen"
- mm_frm_fra_WEB: WEB         "Schwarzer Wertstoff-Großbehälter, Deckel gelb, beschriftet mit 2Wertstoff-Großbehälter (2-wö.)"
- mm_frm_fra_WE4B: WE4B       "Schwarzer Wertstoff-Großbehälter, Deckel gelb, beschriftet mit 4Wertstoff-Großbehälter (4-wö.)"
- mm_ica_gen: iCalendar-Datei laden

Error Log: HA is added

### Logs

```Shell
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 13:30:41 (1 occurrences)
Last logged: 13:30:41
fetch failed for source Müllmax: 
Traceback (most recent call last): 
File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 340, 
in parts validate_token(name) 
File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 128, 
in validate_token raise ValueError(name) 
ValueError: 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"> 
During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, 
in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ 
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/muellmax_de.py", line 148, 
in fetch dates = self._ics.convert(r.text) ^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, 
in convert events: List[Any] = icalevents.events( ^^^^^^^^^^^^^^^^^^ 
File "/usr/local/lib/python3.11/site-packages/icalevents/icalevents.py", line 57, 
in events found_events += parse_events( ^^^^^^^^^^^^^ 
File "/usr/local/lib/python3.11/site-packages/icalevents/icalparser.py", line 288, 
in parse_events calendar = Calendar.from_ical(content) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/usr/local/lib/python3.11/site-packages/icalendar/cal.py", line 330, 
in from_ical name, params, vals = line.parts() ^^^^^^^^^^^^ 
File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 352, 
in parts raise ValueError( 
ValueError: Content line could not be parsed into parts: '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">': <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: muellmax_de
      args:
        service: Rsa
        mm_frm_ort_sel: stadt
        mm_frm_str_sel: strasse
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by IamNeo1** [comment]
It was obviously a problem with the website, which occurs irregularly, the website responds very slowly and when starting HA nothing came back several times. After 4 restarts HA has received the ICS. With all kinds of garbage dates. A query of the wished types in the wizard and args in the config would be much better.

I will open a request for this.

**Comment by IamNeo1** [comment]
The error occurs again and again. Each time the calendar is empty afterwards. So this extension cannot be used.

**Comment by Isengo1989** [comment]
Any news on that one?

**Comment by GitPat2** [comment]
Does not work here either :-(

**Comment by BergCyrill** [comment]
Since I did have the same issue: The PR #2471 fixed the issue above for me. Currently not released but I have copied the content from muellmax_de.py

**Comment by GitPat2** [comment]
2.1.0 does not work for me: "Die Quelle hat eine ungültige Antwort zurückgegeben: "Got invalid response from the server, please recheck your arguments". Bitte überprüfe die Argumente und versuche es erneut."

**Comment by aschmitz-GH** [comment]
same for me, also the muellmax_de.py does not work (see other issue)

**Comment by lxffm** [comment]
Same for me, I can't actually configure the integration at all.

Die Quelle hat eine ungültige Antwort zurückgegeben: "Got invalid response from the server, please recheck your arguments". Bitte überprüfe die Argumente und versuche es erneut.

Where do I actually get the value for service: from? I picked Germany / Maintal from the setup GUI, and it put "Mai" in the service field. I don't have a clue, whether this is the issue or whether the muellmax_de Service is not responding correctly.

**Comment by hendrik001973** [comment]
Same here. I picked RSAG from Muellmax_de.

**Comment by aschmitz-GH** [comment]
After I downloaded the new Version of muellmax_de.py from GIT and exchanged it in HA, it worked fine.

**Comment by hendrik001973** [comment]
> After I downloaded the new Version of muellmax_de.py from GIT and exchanged it in HA, it worked fine.

Where do I find it? Thanks in advance!

**Comment by aschmitz-GH** [comment]
> > After I downloaded the new Version of muellmax_de.py from GIT and exchanged it in HA, it worked fine.
> 
> Where do I find it? Thanks in advance!

i updated my comment.
You should find it here:
https://github.com/mampfes/hacs_waste_collection_schedule/tree/master/custom_components/waste_collection_schedule/waste_collection_schedule/wizard

**Comment by hendrik001973** [comment]
Thanks, that worked, but only for a while...

After a Restart of Home Assistant the entities were not accessible and when I wanted to repeat the process again, I got the response "Unknown error occurred".

**Comment by hendrik001973** [comment]
I already have the new version of this file, but it seems, that it only works on a small number of tries

**Comment by magicbenny** [comment]
Had to reinstall the integration today due to some other reasons. Version 2.8.0 seems to still not working with Müllmax and Rsa. :(

**Comment by bbr111** [comment]
testet source.
GUI Setup and yaml Test ok
close issue.
