### ISSUE TITLE
[Bug]: HTTP 403 Landkreis Karlsruhe

### ISSUE THREAD

**Issue by phbasler** [mampfes/hacs_waste_collection_schedule#1543]
### I Have A Problem With:

A specific source

### What's Your Problem

The example for Karlsruhe does not work anymore.
I get a HTTP 403 error 

~~~
fetch failed for source ICS: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 179, in fetch return self.fetch_url(self._url, self._params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 197, in fetch_url r.raise_for_status() File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://waste.awb-landkreis-karlsruhe.de/WasteManagementKarlsruheHaushalteBlank/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=717948001&AboID=60498&Fra=RC2;RC1;BT2;BC;RT;Schad;WC;WT;BT1

~~~

I get the same error if I run wget with 

~~~
 wget 'https://waste.awb-landkreis-karlsruhe.de/WasteManagementKarlsruheHaushalteBlank/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=717948001&AboID=60498&Fra=RC2;RC1;BT2;BC;RT;Schad;WC;WT;BT1'


--2023-12-20 21:41:27--  https://waste.awb-landkreis-karlsruhe.de/WasteManagementKarlsruheHaushalteBlank/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=717948001&AboID=60498&Fra=RC2;RC1;BT2;BC;RT;Schad;WC;WT;BT1
Resolving waste.awb-landkreis-karlsruhe.de (waste.awb-landkreis-karlsruhe.de)... 85.115.16.149
Connecting to waste.awb-landkreis-karlsruhe.de (waste.awb-landkreis-karlsruhe.de)|85.115.16.149|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-12-20 21:41:27 ERROR 403: Forbidden.
~~~

### Source (if relevant)

https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/awb_landkreis_karlsruhe_de.md

### Logs

```Shell
fetch failed for source ICS: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 179, in fetch return self.fetch_url(self._url, self._params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 197, in fetch_url r.raise_for_status() File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://waste.awb-landkreis-karlsruhe.de/WasteManagementKarlsruheHaushalteBlank/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=717948001&AboID=60498&Fra=RC2;RC1;BT2;BC;RT;Schad;WC;WT;BT1
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by phbasler** [comment]
I just noticed that the resource is blocked also on the webpage for some of my devices, but not all.

**Comment by 5ila5** [comment]
I can not reproduce this Issue. The test case works just fine on my end 
```shell
./custom_components/waste_collection_schedule/waste_collection_schedule/test/test_sources.py -y awb_landkreis_karlsruhe_de -it 
Testing ICS awb_landkreis_karlsruhe_de
  found 67 entries for Adlerstr. 1, 76694 Forst
```
```shell
❯ wget 'https://waste.awb-landkreis-karlsruhe.de/WasteManagementKarlsruheHaushalteBlank/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=717948001&AboID=60498&Fra=RC2;RC1;BT2;BC;RT;Schad;WC;WT;BT1'
--2023-12-21 16:41:49--  https://waste.awb-landkreis-karlsruhe.de/WasteManagementKarlsruheHaushalteBlank/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=717948001&AboID=60498&Fra=RC2;RC1;BT2;BC;RT;Schad;WC;WT;BT1
CA-Zertifikat »/etc/ssl/certs/ca-certificates.crt« wurde geladen
Auflösen des Hostnamens waste.awb-landkreis-karlsruhe.de (waste.awb-landkreis-karlsruhe.de)… 85.115.16.149
Verbindungsaufbau zu waste.awb-landkreis-karlsruhe.de (waste.awb-landkreis-karlsruhe.de)|85.115.16.149|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 200
Länge: nicht spezifiziert [text/calendar]
Wird in »WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=717948001&AboID=60498&Fra=RC2;RC1;BT2;BC;RT;Schad;WC;WT;BT1.1« gespeichert.

WasteManagementServiceServlet?ApplicationName=Calenda     [ <=>                                                                                                                   ]  39,54K  --.-KB/s    in 0,02s

2023-12-21 16:41:49 (1,87 MB/s) - »WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=717948001&AboID=60498&Fra=RC2;RC1;BT2;BC;RT;Schad;WC;WT;BT1.1« gespeichert [40488]
```

**Comment by phbasler** [comment]
It seems to be some problem with my network configuration/device configuration.
I would keep this issue open and update it once I found the issue. Maybe someone in the future faces the same problem

**Comment by phbasler** [comment]
In the end it was resolved after a reboot of the pc and the router
