### ISSUE TITLE
[Bug]: Issue with specific ICS file

### ISSUE THREAD

**Issue by jmerifjKriwe** [mampfes/hacs_waste_collection_schedule#1624]
### I Have A Problem With:

A specific source

### What's Your Problem

Updating my usual (online) waste ICS source is creating an exception.
I checked the file (via URL) at https://icalendar.org/validator.html and it seems to be valid. Importing to Google Calender also works without any issue.

(running 9cdf461)

### Logs

```Shell
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 09:41:44 (1 occurrences)
Last logged: 09:41:44

fetch failed for source ICS: Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 340, in parts validate_token(name) File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 128, in validate_token raise ValueError(name) ValueError: <!doctype html> During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 164, in fetch entries = self.fetch_url(url, self._params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 204, in fetch_url return self._convert(r.text) ^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 215, in _convert dates = self._ics.convert(data) ^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, in convert events: List[Any] = icalevents.events( ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( ^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalevents/icalparser.py", line 288, in parse_events calendar = Calendar.from_ical(content) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalendar/cal.py", line 330, in from_ical name, params, vals = line.parts() ^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 352, in parts raise ValueError( ValueError: Content line could not be parsed into parts: '<!doctype html>': <!doctype html>
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://www.niddatal.de/abfallkalender/abfallkalender_boenstadt_{%Y}.ics
      customize:
        - type: Tonnentausch
          show: false
        - type: Christbaum Abholung
          show: false
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by jmerifjKriwe** [comment]
Sorry, I'm so stupid.
They change one letter of the URL from lowercase to uppercase. And I've not been able to recognize it :-/
