### ISSUE TITLE
[Bug]: aha Region Hannover isn't working anymore

### ISSUE THREAD

**Issue by hspe98** [mampfes/hacs_waste_collection_schedule#1656]
### I Have A Problem With:

A specific source

### What's Your Problem

The sensor for aha Region Hannover doesn't work anymore. I think there is an issue with the page parsing process. In 2023 everything worked fine. Example config isn't working too.

When I run 
`curl -X POST -d 'ical_apple=11&hausnr=1&hausnraddon=&strasse=71740%40Am%20Rotdorn%20%2F%20N%C3%B6pke%40N%C3%B6pke' 'https://www.aha-region.de/abholtermine/abfuhrkalender' -v`

I get this output:

```Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying [2a02:790:5:100::2]:443...
* Connected to www.aha-region.de (2a02:790:5:100::2) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=www.aha-region.de
*  start date: Dec 21 00:30:14 2023 GMT
*  expire date: Mar 20 00:30:13 2024 GMT
*  subjectAltName: host "www.aha-region.de" matched cert's "www.aha-region.de"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* using HTTP/2
* h2h3 [:method: POST]
* h2h3 [:path: /abholtermine/abfuhrkalender]
* h2h3 [:scheme: https]
* h2h3 [:authority: www.aha-region.de]
* h2h3 [user-agent: curl/7.88.1]
* h2h3 [accept: */*]
* h2h3 [content-length: 96]
* h2h3 [content-type: application/x-www-form-urlencoded]
* Using Stream ID: 1 (easy handle 0x5590768760)
> POST /abholtermine/abfuhrkalender HTTP/2
> Host: www.aha-region.de
> user-agent: curl/7.88.1
> accept: */*
> content-length: 96
> content-type: application/x-www-form-urlencoded
>
* We are completely uploaded and fine
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200
< strict-transport-security: max-age=31536000
< date: Wed, 10 Jan 2024 00:20:32 GMT
< server: Apache
< x-powered-by: PHP/8.2.13
< expires: Sat, 26 Jul 1997 05:00:00 GMT
< cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< pragma: no-cache
< content-disposition: inline; filename="calendar-Restabfall.ics"
< content-description: File Transfer
< content-transfer-encoding: binary
< strict-transport-security: max-age=31536000
< access-control-allow-origin: *
< last-modified: Wed, 10 Jan 2024 00:20:32 GMT
< content-length: 0
< vary: User-Agent
< x-ua-compatible: IE=edge
< x-content-type-options: nosniff
< content-type: text/calendar; charset="UTF-8"
<
* Connection #0 to host www.aha-region.de left intact
```

As you can see, the content-length is 0.

### Source (if relevant)

aha_region_de

### Logs

```Shell
2024-01-10 01:02:13.677 ERROR (SyncWorker_4) [waste_collection_schedule.source_shell] fetch failed for source Zweckverband Abfallwirtschaft Region Hannover:
Traceback (most recent call last):
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch
entries = self._source.fetch()
^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/aha_region_de.py", line 117, in fetch
dates = self._ics.convert(r.text)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, in convert
events: List[Any] = icalevents.events(
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/icalevents/icalevents.py", line 57, in events
found_events += parse_events(
^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/icalevents/icalparser.py", line 286, in parse_events
raise ValueError("Content is invalid!")
ValueError: Content is invalid!
```

### Relevant Configuration

```YAML
`waste_collection_schedule:
    sources:
    - name: aha_region_de
      args:
        gemeinde: Neustadt a. Rbge.
        strasse: Am Rotdorn / Nöpke
        hnr: "1"
        zusatz: ""
`
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by Lansolo81** [comment]
Same problem here.

**Comment by kwithus** [comment]
same here

**Comment by hspe98** [comment]
Its now seems to work again, but showing the wrong date:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/7887268/1e6f6855-65a2-4d4b-879e-ef620a973615)
Usually and according to aha the waste gets collected at Thursdays:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/7887268/61322989-896f-4530-85ee-311bef09b8d4)

Maybe someone can dig a bit deeper.
