### ISSUE TITLE
[Bug]: Stadtreinigung Leipzig not working

### ISSUE THREAD

**Issue by jankete** [mampfes/hacs_waste_collection_schedule#1721]
### I Have A Problem With:

A specific source

### What's Your Problem

Hi, Stadtreiningung Leipzig seems not working anymore. I the HA-Log, I can read something about "Maintenance Mode", but the website (https://stadtreinigung-leipzig.de/wir-kommen-zu-ihnen/abfallkalender) is doing fine.

### Source (if relevant)

stadtreinigung_leipzig_de

### Logs

```Shell
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 12:15:45 (1 occurrences)
Last logged: 12:15:45

fetch failed for source Stadtreinigung Leipzig: Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 340, in parts validate_token(name) File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 128, in validate_token raise ValueError(name) ValueError: Curently in Maintenance Mode. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/stadtreinigung_leipzig_de.py", line 52, in fetch dates = self._ics.convert(r.text) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, in convert events: List[Any] = icalevents.events( ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( ^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalevents/icalparser.py", line 288, in parse_events calendar = Calendar.from_ical(content) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalendar/cal.py", line 330, in from_ical name, params, vals = line.parts() ^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 352, in parts raise ValueError( ValueError: Content line could not be parsed into parts: 'Curently in Maintenance Mode.': Curently in Maintenance Mode.
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: stadtreinigung_leipzig_de
      args:
        street: ***straße
        house_number: 10
```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by jankete** [comment]
Maybe it is just a "trailing slash problem" somewhere in the code.

"https://stadtreinigung-leipzig.de/wir-kommen-zu-ihnen/abfallkalender" leads to the right page where I can have a look for the dates.

"https://stadtreinigung-leipzig.de/wir-kommen-zu-ihnen/abfallkalender**/**" redirects to "https://stadtreinigung-leipzig.de/wir-kommen-zu-ihnen/abfallkalender/backup-abfallkalender" which is mailny the start page without the option to look for the dates.

**Comment by jankete** [comment]
Working again since 1.45.1
