### ISSUE TITLE
fetch failed for source ICS

### ISSUE THREAD

**Issue by chrheld** [mampfes/hacs_waste_collection_schedule#176]
Unfortunately, in the combination of Home Assistant 2022.3.4 and Waste Collection Schedule 1.16.0, I get the following error message in the log. The entries from the google calendar are no longer loaded.

========================================
Logger: waste_collection_schedule.scraper
Source: custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py:118
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 16:56:57 (1 occurrences)
Last logged: 16:56:57

fetch failed for source ICS: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", line 116, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 178, in fetch return self.fetch_url(self._url, self._params) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 202, in fetch_url return self._convert(r.text) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 209, in _convert dates = self._ics.convert(data) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 28, in convert events = icalevents.events( File "/usr/local/lib/python3.9/site-packages/icalevents/icalevents.py", line 50, in events found_events += parse_events(content, start=start, end=end) File "/usr/local/lib/python3.9/site-packages/icalevents/icalparser.py", line 356, in parse_events for dt in rule.between(after, end, inc=True): File "/usr/local/lib/python3.9/site-packages/dateutil/rrule.py", line 283, in between for i in gen: File "/usr/local/lib/python3.9/site-packages/dateutil/rrule.py", line 1401, in _iter while exlist and exlist[0] < ritem: File "/usr/local/lib/python3.9/site-packages/dateutil/rrule.py", line 1338, in __lt__ return self.dt < other.dt TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by mampfes** [comment]
Please try to add `version: 1` to your ICS configuration (see also [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md)).
