### ISSUE TITLE
Stadtreinigung Hamburg stopped working[Bug]: 

### ISSUE THREAD

**Issue by HunZ83** [mampfes/hacs_waste_collection_schedule#1769]
### I Have A Problem With:

A specific source

### What's Your Problem

Stadtreinigung Hamburg stopped working. Unfortunately, I cannot understand the logfile and hope, you can help me.

### Logs

```Shell
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 15:18:14 (1 occurrences)
Last logged: 15:18:14

Setup failed for custom integration 'waste_collection_schedule': Unable to import component: No module named 'waste_collection_schedule.source_shell'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 21, in <module>
    from waste_collection_schedule import Customize, SourceShell  # type: ignore # isort:skip # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/__init__.py", line 3, in <module>
    from .source_shell import Customize, SourceShell  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'waste_collection_schedule.source_shell'
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
stadtreinigung_hamburg returns entries for me.
The log looks like you messed up your installation of this integration as it tries to find source_shell but cannot find it. 

You can look at your files there should be a file custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py, but the error suggests there isn't.

Try reinstalling this integration

**Comment by HunZ83** [comment]
Thank you. It works fine after reinstalling the integration.

**Comment by HunZ83** [comment]
.
