### ISSUE TITLE
[Bug]: No Dates being pulled - Somerset

### ISSUE THREAD

**Issue by OneScuzzie2k** [mampfes/hacs_waste_collection_schedule#1773]
### I Have A Problem With:

The integration in general

### What's Your Problem

I have set it to somerset, it pulled one date today, and not added any other dates, I have re-added it from HACS but still no data being pulled. I cannot see anything or errors that look obvious in the Logs.

### Logs

```Shell
Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421
First occurred: 11:13:23 (5 occurrences)
Last logged: 11:14:23
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/events_asyncio.py", line 138, in notify
    variables = parse_event_xml(content)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/events_base.py", line 104, in parse_event_xml
    value = from_didl_string(value)[0]
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/data_structures_entry.py", line 31, in from_didl_string
    root = XML.fromstring(string.encode("utf-8"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/xml/etree/ElementTree.py", line 1338, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 372
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by OneScuzzie2k** [comment]
I have removed completely and re-added I seem to only get todays collection nothing else. Here is my setup: 

  - platform: waste_collection_schedule
    name: next_recycling_collection
    details_format: generic
    types:
      - Recycling
    value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'
  - platform: waste_collection_schedule
    name: next_food_collection
    details_format: generic
    types:
      - Food
    value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'
  - platform: waste_collection_schedule
    name: next_refuse_collection
    details_format: generic
    types:
      - Refuse
    value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'
  - platform: waste_collection_schedule
    name: next_garden_collection
    details_format: generic
    types:
      - Garden
    value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'

**Comment by OneScuzzie2k** [comment]
waste_collection_schedule:
  sources:
    - name: iweb_itouchvision_com
      args:
        postcode: "B*** ***"
        uprn: "30****"
        council: "SOMERSET"
      calendar_title: "SSDC Collection"

**Comment by OneScuzzie2k** [comment]
Still not working? anyone?

**Comment by OneScuzzie2k** [comment]
Thanks mine all of sudden started working yesterday!

**Comment by Dukeicon** [comment]
What day is your usual collection?

Before I created the automation to update if the entity(s) were 'unknown', the sensor(s) were showing in HA as unknown for a couple days after my collection day.

**Comment by bbr111** [comment]
is this still active? or can it be closed?

**Comment by Dukeicon** [comment]
@bbr111 this issue relates to the now deprecated iweb_itouchvision_com source that was deprecated in [2.1.0](https://github.com/mampfes/hacs_waste_collection_schedule/releases/tag/2.10.0).

@OneScuzzie2k should migrate over to the [iapp_itouchvision_com](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/iapp_itouchvision_com.md) source if they haven't done so already.

IMO this can be closed.

**Comment by markvp** [comment]
Thanks for the report, and thanks to @Dukeicon for the helpful follow-up.

The `iweb_itouchvision_com` source was deprecated and removed in [v2.10.0](https://github.com/mampfes/hacs_waste_collection_schedule/releases/tag/2.10.0). Somerset is fully supported under the replacement source [`iapp_itouchvision_com`](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/iapp_itouchvision_com.md).

If you're still on a YAML configuration, update `name: iweb_itouchvision_com` to `name: iapp_itouchvision_com` and replace the `council` argument with `municipality: "SOMERSET"`. The `postcode` argument is no longer needed — only `uprn` and `municipality` are required.

Closing this as resolved.
