### ISSUE TITLE
[Source Request]: Moorabool Shire, Victoria, Australia

### ISSUE THREAD

**Issue by beccsjb** [mampfes/hacs_waste_collection_schedule#2150]
### Municipality / Region

Moorabool Shire, Victoria

### Collection Calendar Webpage

https://www.moorabool.vic.gov.au/Waste-and-environment/Household-bins/Find-your-bin-collection-day

### Example Address

1 Harbours Rd, Yendon

### Collection Data Format

Something different (add to additional information)

### Additional Information

Collection day is provided by entering an address on their Map and then you can given your collection day and time. Not sure if anything can be done with this though.

**Comment by pashak44** [comment]
I'd like to second this request. 
Example address:
Canopus Circuit, Long Forest

**Comment by BenBarat** [comment]
Thanks for adding this fix to the collection in the last few hours. I see you have been busy!
I looked at the updated source code (to learn from your code) and noticed only two bin icons showing for Moorabool Shire. They have three bins available (and I was reading that it is proposed for some in NSW Australia to have a fourth purple bin soon for food waste). The code bloat will be HUUUGE!

Could you please add Green Waste collection icon (green lid) after line 35 as well. They have the garbage bin (red lid) every week, and the recycling (yellow lid) and green waste (green lid) alternate weeks.
Website displays for entered address I used:
Garbage collection
Mon 7/7/2025
Recycling collection
Mon 7/7/2025
Green waste collection
Mon 14/7/2025

Note: The calendar now correctly shows the three bins.

Thank you.

**Comment by Rayvenhaus** [comment]
I really appreciate everything everyone involved is doing with this project; it is incredible. As mentioned above, I've noticed that the integration for Moorabool Shire in Victoria, Australia, is available on the repository; however, it's not yet included in the 2.9.0 release.  When will this be included and released?

**Comment by BenBarat** [comment]
It **WAS** working, but not recently. 
Again, like Blacktown NSW Australia https://github.com/mampfes/hacs_waste_collection_schedule/issues/4434 , it is not working. Same issues? The header user agent seems to be a little different, so won't able to use the same workaround.

Comment: Test case for Blacktown seemed to have bled into this file as well.

I note there are two other open requests for Moorabool which may also have relevant information:
https://github.com/mampfes/hacs_waste_collection_schedule/issues/3996
https://github.com/mampfes/hacs_waste_collection_schedule/issues/3048

**Comment by BenBarat** [comment]
While looking at some tweaks, could you please note the following:
in moorabool_vic_gov_au.md the url points to Blacktown, not Moorabool on line 3.

`Support for schedules provided by [Moorabool Shire Council Waste and Recycling](https://www.blacktown.nsw.gov.au/Services/Waste-services-and-collection/Waste-collection-days).`
should read:
`Support for schedules provided by [Moorabool Shire Council Waste and Recycling](https://www.moorabool.vic.gov.au/Waste-and-environment/Household-bins/Find-your-bin-collection-day).`

and the example currently reads:
```
  sources:
    - name: blacktown_nsw_gov_au
      args:
        address: 18 Campbell Street, Blacktown, NSW 2148
```
but should probably say:
```
  sources:
    - name: moorabool_vic_gov_au
      args:
        address: 139 Main Street Bacchus Marsh 3340

```


moorabool_vic_gov_au.py line 26 and 27 point to a Blacktown, not Moorabool address. Maybe use 139 Main Street Bacchus Marsh 3340 instead (it's the local Border Inn pub) viz:
```
TEST_CASES = {
    "Border Inn Hotel": {
        "address": "139 Main Street Bacchus Marsh 3340",
```
and
```
    "Bendigo Bank": {
        "address": "191 Main Street Bacchus Marsh 3340",
```

**Comment by markvp** [comment]
Moorabool is already supported via the `moorabool_vic_gov_au` source. Closing as already supported.

**Comment by BenBarat** [comment]
Um, it's broken again:
System error log say the following:
This error originated from a custom integration.

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
integration: Waste Collection Schedule (documentation)
First occurred: 6:24:48 pm (1 occurrence)
Last logged: 6:24:48 pm

fetch failed for source Moorabool Shire Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/moorabool_vic_gov_au.py", line 83, in fetch data = self.search_address(self.address, session) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/moorabool_vic_gov_au.py", line 76, in search_address return json.loads(r.text) ~~~~~~~~~~^^^^^^^^ File "/usr/local/lib/python3.14/json/__init__.py", line 352, in loads return _default_decoder.decode(s) ~~~~~~~~~~~~~~~~~~~~~~~^^^ File "/usr/local/lib/python3.14/json/decoder.py", line 345, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.14/json/decoder.py", line 363, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

See comments in https://github.com/mampfes/hacs_waste_collection_schedule/issues/4434 and https://github.com/mampfes/hacs_waste_collection_schedule/issues/2505 as well.

Header issues?

Can we add a little non-Blacktown luv to this site, viz .md file etc?
