### ISSUE TITLE
[Bug]: fetch failed for source Apps by Abfall+: 

### ISSUE THREAD

**Issue by chma73** [mampfes/hacs_waste_collection_schedule#2184]
### I Have A Problem With:

The integration in general

### What's Your Problem

After HA update to Core version 2024.6.4 waste collection creates a failure and stops working

### Logs

```Shell
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:147
Integration: waste_collection_schedule (Dokumentation)
Erstmals aufgetreten: 08:46:33 (1 Vorkommnisse)
Zuletzt protokolliert: 08:46:33

fetch failed for source Apps by Abfall+: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py", line 183, in fetch for d in self._app.generate_calendar(): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 929, in generate_calendar self.select_street() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 710, in select_street raise Exception( Exception: Street 'alle Straßen' not found. available: ['Albert-Schweitzer-Str.', 'Albrecht-Dürer-Str.', 'Alleeweg', 'Allerseeweg', 'Alte Steige', 'Alter Weinberg', 'Am Funkturm', 'Am Hessental', 'Am Judengarten', 'Am Klettenrain', 'Am Kreutweg', 'Am Losbaum', 'Am Malbaum', 'Am Pfad', 'Am Reele', 'Am Schindanger', 'Am Sonnenhang', 'Am Trieb', 'Am Ziegelbaum', 'An den Forstäckern', 'An der Frankenwarte', 'Aschaffenburger Str.', 'Augsburger Weg', 'Balthasar-Neumann-Str.', 'Bamberger Weg', 'Bayernstr.', 'Bergmannweg', 'Bergstr.', 'Brunnengasse', 'Bürgermeister-Seubert-Str.', 'Burkardusweg', 'Büttelbrunner Pfad', 'Drosselweg', 'Eduard-Buchner-Str.', 'Einsteinstr.', 'Falkenweg', 'Fasanenstr.', 'Finkenstr.', 'Florian-Geyer-Weg', 'Frankenstr.', 'Friedbergweg', 'Friedrich-Ebert-Str.', 'Friedrich-Koenig-Weg', 'Friedrich-von-Spee-Str.', 'Gänsweide', 'Gartenstr.', 'Greinbergweg', 'Grundweg', 'Gustav-Heinemann-Allee', 'Hans-Sachs-Str.', 'Hauptstr.', 'Heidelberger Str.', 'Heinrich-Lübke-Str.', 'Heisenbergstr.', 'Herrenweg', 'Hüttenweg', 'Im Graben', 'Im Roth', 'Im Wiesengrund', 'Jägerstr.', 'Jahnstr.', 'Kalkofenweg', 'Kapellenweg', 'Karwinkel', 'Kiesweg', 'Kirchgasse', 'Kister Str.', 'Klinggraben', 'Krautgartenweg', 'Leibnizstr.', 'Leistenstr.', 'Lerchenweg', 'Leutfresserweg', 'Liebigstr.', 'Lindengasse', 'Luzer Str.', 'Martin-Luther-Str.', 'Martin-Wilhelm-Str.', 'Matthias-Grünewald-Str.', 'Matzenhecke', 'Max-Planck-Str.', 'Mehlenweg', 'Münchener Str.', 'Nikolausweg', 'Norbertstr.', 'Obere Landwehr', 'Oberes Hessental', 'Otto-Hahn-Str.', 'Pfarrer-Fleckenstein-Str.', 'Pfarrer-Hußlein-Str.', 'Quellenstr.', 'Rebenweg', 'Riesgasse', 'Roter Rain', 'Rübezahlweg', 'Rudolf-Harbig-Platz', 'Schulgasse', 'Schwabenäcker', 'Schwarze Erde', 'Schwedenweg', 'Seckertswiesenweg', 'Seeweg', 'Sonnemannstr.', 'Spechtweg', 'St.-Bruno-Str.', 'Stegweg', 'Steiggasse', 'Steinweg', 'Tannenweg', 'Theodor-Heuss-Str.', 'Thüringer Str.', 'Tilman-Riemenschneider-Str.', 'Via Bastia', 'Wagnergäßchen', 'Waldstr.', 'Wallweg', 'Wasenweg', 'Weg zum Kreuz', 'Wiesenweg', 'Winterleitenweg', 'Wirtgasse', 'Würzburger Str.']
```

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: app_abfallplus_de
      args:
        app_id: de.k4systems.teamorange
        city: Höchberg
        strasse: alle Straßen
        hnr: alle Hausnummern
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
I think the error message is pretty clear: `Street 'alle Straßen' not found. available: ['Albert-Schweitzer-Str.', 'Albrecht-Dürer-Str.', 'Alleeweg', 'Allerseeweg', 'Alte Steige', 'Alter Weinberg',[...]]`

Seems like you know need to define a real street for Höchberg. 
This works:
```yaml
waste_collection_schedule:
    sources:
    - name: app_abfallplus_de
      args:
        app_id: de.k4systems.teamorange
        city: Höchberg
        strasse: Allerseeweg
        hnr: 3
```

**Comment by chma73** [comment]
@5ila5 interesting, I tried this when I installed waste collection initial, at that time it didn't work with the house number and street - only with the setup "all". Then something seems to have changed. Thanks with your support it works again.
