### ISSUE TITLE
[Bug]: abfall_havelland_de.md - stops working after time

### ISSUE THREAD

**Issue by adieball** [mampfes/hacs_waste_collection_schedule#2205]
### I Have A Problem With:

A specific source

### What's Your Problem

I configured waste collection as described and it’s working fine, but after a while it seems there is no update anymore.
I believe it’s related to some sort of cockles required when calling anything from the website including the ics.

when I manually go to the website and go through he process of getting the url again (Which is exactly the same URL as before) it works again for a while (some days) and the stops again.

copying the url into a browser does indeed bring Error 404

### Logs

```Shell
Logger: waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:147
Integration: waste_collection_schedule (Dokumentation)
Erstmals aufgetreten: 10:16:44 (1 Vorkommnisse)
Zuletzt protokolliert: 10:16:44

fetch failed for source ICS: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 179, in fetch return self.fetch_url(self._url, self._params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 198, in fetch_url r.raise_for_status() File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.abfall-havelland.de/UserFiles/Files/Abfuhrtermine%20Glockenheidering%20Wustermark%20OT%20Elstal.ics
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Looks like they generate the files and save them at the cache folder which is cleared regularly, you can either download the ICS and reference the file in HA or use the newly created source (#2213), which will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
