### ISSUE TITLE
[Bug]: ecoharmonogram - unable to match town

### ISSUE THREAD

**Issue by minchal** [mampfes/hacs_waste_collection_schedule#2223]
### I Have A Problem With:

A specific source

### What's Your Problem

With the below yaml config (anonymized), in the logs I see error:
`.../source/ecoharmonogram_pl.py", line 118, in fetch raise Exception( Exception: Found multiple matches but no exact match found ['town: Domaszczyn, district:Długołęka', 'town: Domaszczyn Mały, district:Długołęka'] `

By quick code review it seems that problem is related to usage of `in` operator instead of exact match while in this case there is no additional property I could use to distinguish the items?
Maybe additional config property/flag could be added to use exact match instead of `in`? Or in case of multiple matches additional exact filtering should be executed?

### Source (if relevant)

ecoharmonogram_pl

### Logs

```Shell
fetch failed for source Ecoharmonogram: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ecoharmonogram_pl.py", line 118, in fetch raise Exception( Exception: Found multiple matches but no exact match found ['town: Domaszczyn, district:Długołęka', 'town: Domaszczyn Mały, district:Długołęka']
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: ecoharmonogram_pl
      args:
        town: Domaszczyn
        street: xxx
        house_number: xx
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by minchal** [comment]
Just found that exact matching is already implemented, but in my case I need to add `district` property in the config.
