### ISSUE TITLE
[Bug]: Parsing error in street options. 

### ISSUE THREAD

**Issue by mPolaczek** [mampfes/hacs_waste_collection_schedule#2273]
### I Have A Problem With:

A specific source

### What's Your Problem

The integration unfortunately does not work with the source due to the problem with the road. 

### Source (if relevant)

de.k4systems.hebhagen

### Logs

```Shell
Search your street you will be given some options to choose from:
Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 393, in extract_onclicks
    to_return.append(json.loads(string))
                     ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 28 (char 27)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/wizard/app_abfallplus_de.py", line 212, in <module>
    main()
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/wizard/app_abfallplus_de.py", line 189, in main
    street = select_street(app, bund_select)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/wizard/app_abfallplus_de.py", line 119, in select_street
    streets = app.get_streets(inquirer.prompt(questions)["street_search"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 720, in get_streets
    for a in extract_onclicks(r):
             ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 395, in extract_onclicks
    raise Exception(f"Failed to parse '{string}', onclick: '{onclick}'")
Exception: Failed to parse '["3055|0|\"Oedenburgstraße 	restliche Bereiche/Hausnummern\"","\"Oedenburgstraße 	restliche Bereiche/Hausnummern\"","strasse","fertig","",{}]', onclick: 'awk_standort_auswahl_step_fertig('3055|0|"Oedenburgstraße 	restliche Bereiche/Hausnummern"','"Oedenburgstraße 	restliche Bereiche/Hausnummern"','strasse','fertig','',{})'
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
The tab in the street name destroyed the source (nothing we encountered in any other app we tested before)

fixed in #2276

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
