### ISSUE TITLE
[Bug]: Region AHA - Shows "unknown" 

### ISSUE THREAD

**Issue by YuulGer** [mampfes/hacs_waste_collection_schedule#2414]
### I Have A Problem With:

A specific source

### What's Your Problem

My sensors aren't showing anything.

When I tried to configure a source via integration I get "Invalid response from server, check you configuration if it is correct.".

### Source (if relevant)

AHA - Zweckverband Abfallwirtschaft Region Hannover

### Logs

```Shell
fetch failed for source Zweckverband Abfallwirtschaft Region Hannover: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/aha_region_de.py", line 103, in fetch raise Exception( Exception: Invalid response from server, check you configuration if it is correct.
```

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: aha_region_de
      args:
        gemeinde: Neustadt a. Rbge.
        strasse: Am Rotdorn / Nöpke
        hnr: "1"
        zusatz: ""
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by YuulGer** [comment]
Duplicate https://github.com/mampfes/hacs_waste_collection_schedule/issues/2367
