### ISSUE TITLE
[Bug]: Portenf Source Issue

### ISSUE THREAD

**Issue by illuzn** [mampfes/hacs_waste_collection_schedule#2490]
### I Have A Problem With:

A specific source

### What's Your Problem

The fetch fails with the error below.

This is the calendar state when the error occurs (address redacted for privacy)

![image](https://github.com/user-attachments/assets/7a8faff6-f138-44b4-a85f-b3101dac6ff4)

### Source (if relevant)

portenf_sa_gov_au

### Logs

```Shell
fetch failed for source Port Adelaide Enfield, South Australia: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/portenf_sa_gov_au.py", line 175, in fetch "other-month" in today_div.attrs["class"] ^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'attrs'
```

### Relevant Configuration

```YAML
Not Applicable
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by illuzn** [comment]
Sorry to keep doing this to you.

**Comment by 5ila5** [comment]
AHHHHHHH
They changed the logic and do not highlight today anymore, but the next collection day.

I think this is one of the worst sources.
