### ISSUE TITLE
[Bug]: muellmax_de.py no streets are displayed after selecting any service provider

### ISSUE THREAD

**Issue by aschmitz-GH** [mampfes/hacs_waste_collection_schedule#2515]
### I Have A Problem With:

A specific source

### What's Your Problem

Ran the muellmax_de.py script and was able to select the service provider.
After that the question for the street was displayed but no streets to select.
Tried other service provider but there is the same.

### Logs

```Shell
(vm_waste) homeassistant:/config/custom_components/waste_collection_schedule/waste_collection_schedule/wizard# python muellmax_de.py
[?] Select service provider for district: 
   AWISTA Düsseldorf
 > RSAG Rhein-Sieg-Kreis
   USB Bochum
   Abfallwirtschaftsbetriebe Münster
   Entsorgungsbetrieb Stadt Mainz
   EVS Entsorgungsverband Saar
   Landkreis Gießen
   Stadt Hamm
   Stadt Darmstadt
   TBR Remscheid
   Stadtbildpflege Kaiserslautern
   Stadt Hanau
   Stadt Maintal

[?] Select street: 

Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/wizard/muellmax_de.py", line 207, in <module>
    main()
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/wizard/muellmax_de.py", line 168, in main
    answers = inquirer.prompt(questions)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/wizard/vm_waste/lib/python3.12/site-packages/inquirer/prompt.py", line 11, in prompt
    answers[question.name] = render.render(question, answers)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/wizard/vm_waste/lib/python3.12/site-packages/inquirer/render/console/__init__.py", line 38, in render
    return self._event_loop(render)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/wizard/vm_waste/lib/python3.12/site-packages/inquirer/render/console/__init__.py", line 52, in _event_loop
    self._process_input(render)
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/wizard/vm_waste/lib/python3.12/site-packages/inquirer/render/console/__init__.py", line 109, in _process_input
    render.process_input(ev.value)
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/wizard/vm_waste/lib/python3.12/site-packages/inquirer/render/console/_list.py", line 82, in process_input
    value = self.question.choices[self.current]
            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
IndexError: list index out of range
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
The source had the same problem and I forgot to also patch the wizard

it's fixed in #2519
