### ISSUE TITLE
[Bug]: Sensor can't be created

### ISSUE THREAD

**Issue by Triskelen** [mampfes/hacs_waste_collection_schedule#2578]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

i added following code to my configuration.yaml

`  - platform: waste_collection_schedule
    name: AFVAL
    value_template: 'in {{value.daysTo}} days'
    source_index: [0, 1]
    details_format: upcoming
    count: 1
    types:
      - Restafval
      - PMD
      - Papier en Karton`
      
   and it does not create a sensor

### Logs

```Shell
Logger: homeassistant.components.sensor
Bron: helpers/entity_platform.py:364
integratie: Sensor (documentatie, problemen)
Eerst voorgekomen: 22:57:33 (1 gebeurtenissen)
Laatst gelogd: 22:57:33

Error while setting up waste_collection_schedule platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/waste_collection_schedule/sensor.py", line 131, in async_setup_platform
    api = hass.data[DOMAIN].get("YAML_CONFIG")
          ~~~~~~~~~^^^^^^^^
KeyError: 'waste_collection_schedule'
```

### Relevant Configuration

```YAML
`  - platform: waste_collection_schedule
    name: AFVAL
    value_template: 'in {{value.daysTo}} days'
    source_index: [0, 1]
    details_format: upcoming
    count: 1
    types:
      - Restafval
      - PMD
      - Papier en Karton`
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by Triskelen** [comment]
removed the type from the sensor data get following error:

`Logger: homeassistant.components.sensor
Bron: helpers/entity_platform.py:364
integratie: Sensor (documentatie, problemen)
Eerst voorgekomen: 23:10:00 (1 gebeurtenissen)
Laatst gelogd: 23:10:00

Error while setting up waste_collection_schedule platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/waste_collection_schedule/sensor.py", line 131, in async_setup_platform
    api = hass.data[DOMAIN].get("YAML_CONFIG")
          ~~~~~~~~~^^^^^^^^
KeyError: 'waste_collection_schedule'`

**Comment by 5ila5** [comment]
I could only think of tow possibilities that would throw this.

1. You did not configure any source. You always need to configure a source, You can see a list of all sources in the README. In Supported Service Providers you can find a list of all known supported regions/service providers grouped by country. You can follow the link to get detailed documentation on how to configure the respective source. For more general Documentation take a look [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#configuring-waste-collection-schedules)
2. You have a broken installation: Try unistnalling -> restart HA -> reinstall WCS -> restart HA

**Comment by Triskelen** [comment]
all my calendar items are set so i think the source is set correctly. i just followed the list of instructions to set it up 
i did not add it to my configuration.yaml since it was installed using the gui

ill try to reinstall it

**Comment by 5ila5** [comment]
You cannot add YAML configured sensors to Sources created with the GUI as described in the [GUI Limitations section here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#gui-limitations).

There currently is no way to create a sensor accessing different GUI sources. So if you need `source_index: [0, 1]` You need to use the YAML source configuration. I want to resolve this by bringing the [multiple sources wrapper](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/multiple.md) to the GUI, but I haven't done this yet. And we probably need to taggle some fundamentals first to get a good user experience

**Comment by markvp** [comment]
Thanks for the detailed report, and thanks to @5ila5 for the thorough explanation.

To summarise for anyone who finds this issue later: the `KeyError: 'waste_collection_schedule'` error occurs when a YAML sensor definition (`platform: waste_collection_schedule`) tries to reference a source that was configured through the GUI (config entry). This is a known limitation — GUI-configured sources are not accessible from YAML sensor definitions. The two configuration approaches are separate and cannot be mixed.

If you need a sensor combining multiple sources (e.g. `source_index: [0, 1]`), you will need to configure those sources via YAML rather than the GUI. See the [GUI limitations section](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#gui-limitations) in the docs for details.

Closing this as a configuration issue rather than a bug — no code change needed.
