### ISSUE TITLE
West Oxfordshire Source seems to have broken?

### ISSUE THREAD

**Issue by mattsgreen** [mampfes/hacs_waste_collection_schedule#2619]
Both myself and another user using the same (West Oxfordshire) source have started seeing issues this week.  I see the below in the logs: 

`fetch failed for source West Oxfordshire District Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/westoxon_gov_uk.py", line 235, in fetch serialized_state = r.json()["actions"][0]["returnValue"]["response"][ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable`

_Originally posted by @mattsgreen in https://github.com/mampfes/hacs_waste_collection_schedule/issues/818#issuecomment-2331118178_

**Comment by domdomegg** [comment]
This seems to be failing at `westoxon_gov_uk.py:235`. This is because there is an error response back from the server for the request made on line 234:

<details><summary>Error response</summary>

```json
{
    "actions": [
        {
            "id": "123;a",
            "state": "ERROR",
            "returnValue": null,
            "error": [
                {
                    "exceptionEvent": true,
                    "useDefault": true,
                    "event": {
                        "descriptor": "markup://aura:serverActionError",
                        "attributes": {
                            "values": {
                                "error": {
                                    "message": "Interview state is not supplied",
                                    "stackTrace": "",
                                    "id": "-944885593"
                                }
                            }
                        }
                    }
                }
            ]
        }
    ],
    "context": {
        "mode": "PROD",
        "app": "siteforce:communityApp",
        "contextPath": "/s/sfsites",
        "pathPrefix": "",
        "fwuid": "eGx3MHlRT1lEMUpQaWVxbGRUM1h0Z2hZX25NdHFVdGpDN3BnWlROY1ZGT3cyNTAuOC40LTYuNC41",
        "mlr": 1,
        "coos": 1,
        "loaded": {
            "APPLICATION@markup://siteforce:communityApp": "vgD8vvaBHzgKYqb_JQjQdw",
            "COMPONENT@markup://flowruntime:flowRuntimeForFlexiPage": "6vLCX6RcjM4U8N2_kygrQw",
            "COMPONENT@markup://instrumentation:o11ySecondaryLoader": "1JitVv-ZC5qlK6HkuofJqQ"
        },
        "globalValueProviders": [
            {
                "type": "$Global",
                "values": {
                    "eswConfigDeveloperName": {
                        "writable": true,
                        "defaultValue": ""
                    },
                    "isVoiceOver": {
                        "writable": true,
                        "defaultValue": false
                    },
                    "setupAppContextId": {
                        "writable": true,
                        "defaultValue": ""
                    },
                    "density": {
                        "writable": true,
                        "defaultValue": ""
                    },
                    "srcdoc": {
                        "writable": false,
                        "defaultValue": false
                    },
                    "appContextId": {
                        "writable": true,
                        "defaultValue": ""
                    },
                    "dynamicTypeSize": {
                        "writable": true,
                        "defaultValue": ""
                    },
                    "appContextDeveloperName": {
                        "writable": true,
                        "defaultValue": ""
                    }
                }
            }
        ],
        "enableAccessChecks": true,
        "apce": 1,
        "dns": "c",
        "ls": 1,
        "lairn": [],
        "laerc": [],
        "lav": "61",
        "lgef": [
            "com.salesforce.locker.temporaryGate"
        ],
        "mna": {
            "lightning": "interop"
        },
        "arse": 1,
        "acaf": 1,
        "services": [
            "markup://lightning:configProvider",
            "markup://force:salesforceScopedModuleResolver",
            "markup://force:ldsEngineCreator",
            "markup://instrumentation:locatorService"
        ]
    },
    "perfSummary": {
        "version": "core",
        "request": 101,
        "actions": {
            "123;a": {
                "total": 8,
                "db": 0
            }
        },
        "actionsTotal": 8,
        "overhead": 0
    }
}
```

</details>

Unfortunately I'm not sure how to resolve this error - it looks the same as the request made in my browser when going through the steps.

**Comment by CCCowley** [comment]
I am also facing the same issue

**Comment by wirelessmonkey** [comment]
Facing this issue myself trying to set up this integration!

**Comment by mattsgreen** [comment]
I'm assuming it's something WODC has done...

**Comment by tezcooling** [comment]
I've just tried setting this up of the first time on my HomeAssistant (v. 2024.12.5) every time I go through the setup and select west oxfordshire I enter my address and get the following error:

The source returned an invalid response: "'NoneType' object is not subscriptable". Please check the provided arguments and try again.

**Comment by hipsway** [comment]
Just setting this up and get the same error "NoneType" etc...

**Comment by DackelProjects** [comment]
I am also trying to use this source and getting the same issues. Did anyone find  a workaround for this?

**Comment by 5ila5** [comment]
fixed in #4870

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA
Do not  "update" WCS through HACS until the next release, as pressing the update button performs a "downgrade" to the latest release version
