### ISSUE TITLE
Source defect westoxon_gov_uk

### ISSUE THREAD

**Issue by 5ila5** [mampfes/hacs_waste_collection_schedule#2623]
This had been working nicely, but it seems to have broken? 

Both myself and another user using the same (West Oxfordshire) source have started seeing issues this week.  I see the below in the logs: 

`fetch failed for source West Oxfordshire District Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/westoxon_gov_uk.py", line 235, in fetch serialized_state = r.json()["actions"][0]["returnValue"]["response"][ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable`

_Originally posted by @mattsgreen in https://github.com/mampfes/hacs_waste_collection_schedule/issues/818#issuecomment-2331118178_

**Comment by 5ila5** [comment]
closing for #2623
