### ISSUE TITLE
[Bug]: Stirling Council

### ISSUE THREAD

**Issue by fenster89411** [mampfes/hacs_waste_collection_schedule#2782]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

Started a few days ago:
Calendar is now "unknown"

### Source (if relevant)

Stirling.gov.uk

### Logs

```Shell
Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:147
integration: Waste Collection Schedule (documentation)
First occurred: 3:47:50 PM (6 occurrences)
Last logged: 4:13:19 PM

fetch failed for source Stirling.gov.uk: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/stirling_uk.py", line 70, in fetch NextCollection.text.strip().split(REM_STRING1, 1)[0].strip(), ^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'text'
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by fenster89411** [comment]
The route hasn't changed https://www.stirling.gov.uk/bins-and-recycling/bin-collection-dates-search/collections/?route=9748
