### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SomaKhaos** [mampfes/hacs_waste_collection_schedule#2884]
### I Have A Problem With:

A specific source

### What's Your Problem

Everything works fine until a few hours later, when it suddenly stops working. It seems like the server of the source adress refuses the connection at some point.

### Source (if relevant)

https://nu.neu-ulm.de/securedl/sdl-eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjkzNzY3NzUsImV4cCI6MTcyOTQyMzU3NSwidXNlciI6MCwiZ3JvdXBzIjpbMCwtMV0sImZpbGUiOiJmaWxlYWRtaW5cL21vdW50XC9zdGFkdC1udVwvcGRmc1wvMl9CdWVyZ2VyX1NlcnZpY2VcL011ZWxsX3VuZF9TYXViZXJrZWl0XC9BYmZhbGxrYWxlbmRlcl9OVV8yMDI0X0Jlemlya18yLmljcyIsInBhZ2UiOjEwODJ9.bI5uIAEzmH1Gy9GgkggzQ-Y19WXQCbCJqAfRJ2NZnAs/Abfallkalender_NU_2024_Bezirk_2.ics

### Logs

```Shell
Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 02:20:21 (1 Vorkommnisse)
Zuletzt protokolliert: 02:20:21

fetch failed for source ICS: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 193, in fetch entries = self.fetch_url(url, self._params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 229, in fetch_url r.raise_for_status() File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://nu.neu-ulm.de/securedl/sdl-eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjkzMzM1MTQsImV4cCI6MTcyOTM4MDMxNCwidXNlciI6MCwiZ3JvdXBzIjpbMCwtMV0sImZpbGUiOiJmaWxlYWRtaW5cL21vdW50XC9zdGFkdC1udVwvcGRmc1wvMl9CdWVyZ2VyX1NlcnZpY2VcL011ZWxsX3VuZF9TYXViZXJrZWl0XC9BYmZhbGxrYWxlbmRlcl9OVV8yMDI0X0Jlemlya18yLmljcyIsInBhZ2UiOjEwODJ9.RnArCdFHdGgnxPo1xyD--HXiXF7B5ZOUBGzXRpRs4ys/Abfallkalender_NU_2024_Bezirk_2.ics
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment]
The urls have changed. Please go to [https://nu.neu-ulm.de/buerger-service/leben-in-neu-ulm/abfall-sauberkeit/abfallkalender](https://nu.neu-ulm.de/buerger-service/leben-in-neu-ulm/abfall-sauberkeit/abfallkalender), select your Bezirk and copy the new link in your config.

**Comment by SomaKhaos** [comment]
if i copy the link from my "Bezirk" i get exactly the same link as posted in my issue above.

**Comment by SomaKhaos** [comment]
> if i copy the link from my "Bezirk" i get exactly the same link as posted in my issue above.

nvm it wasn't the exact same i just realized

**Comment by SomaKhaos** [comment]
it seems like the link changes every day or two or something like that. it's a complete new one again

**Comment by ReneNulschDE** [comment]
then we need an own source for this and collect the link. Let me check it.

**Comment by SomaKhaos** [comment]
any news on that so far? ☺️
