### ISSUE TITLE
[Bug]: kwu_de source not found

### ISSUE THREAD

**Issue by Jirka-Eh** [mampfes/hacs_waste_collection_schedule#2893]
### I Have A Problem With:

A specific source

### What's Your Problem

2024-10-21 18:29:27.425 ERROR (SyncWorker_4) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] source not found: kwu_de

### Source (if relevant)

kwu_de

### Logs

```Shell
2024-10-21 18:29:27.425 ERROR (SyncWorker_4) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] source not found: kwu_de
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
This should not happen and may indicate a broken install, maybe try removing and re-installing WCS (don't forget to reboot HA)

**Comment by Jirka-Eh** [comment]
I removed WCS, restarted HA, deleted old entities, restarted HA again.
Than I reinstalled WCS and restarted HA.
Add new integration -> WCS -> configure it.
Country: Germany
Source: kwu_de => Unknown error occurred

Maybe the URLs at https://www.kwu-entsorgung.de/ have been changed?

**Comment by 5ila5** [comment]
I cannot reproduce this issue.

> Maybe the URLs at https://www.kwu-entsorgung.de/ have been changed?
> WCS worked perfectly until last week!

No that's not it `source not found: kwu_de` indicates that the source_shell.py script did not find the custom_components/waste_collection_schedule/waste_collection_schedule/source/kwu_de.py file which is there since November 25th, 2022 so it must be some weird/broken installation. Can you check if this file exists?



![image](https://github.com/user-attachments/assets/6f40a21f-1b07-47eb-957a-fa094c5002bb)

**Comment by Jirka-Eh** [comment]
Checked, the file exists!

![image](https://github.com/user-attachments/assets/af4e72d1-e94b-40bc-8686-98ef512d0ad0)

**Comment by Jirka-Eh** [comment]
I tested several german sources. Most of them I can't add!
Sources from other countries are working!

**Comment by meilon** [comment]
I have the same issue with `awb_es_de`
I configure it through yaml, the config hasn't been touched since I added them. I downloaded the WCS source locally and ran the test script after editing the test case in the awb_es_de.py to my settings and it returns the next pickups without issue.
The WCS files are where they are supposed to be, I don't know why (and sadly when after which update) it stopped working

**Comment by 5ila5** [comment]
Seems to be related to #2907

**Comment by Jirka-Eh** [comment]
Ok, I have ICS Calendar installed.
But what can we do?

**Comment by ReneNulschDE** [comment]
What version of ICS Calendar do you have installed? Is the version number is greater then 5.0.2?
if yes, move on - if not share share the version or other custom components.

You can wait until a general solution is available (needs an update of the underlying lib icalevents) - (best option for "normal" users)
Or...

I TESTED THIS JUST IN MY ENVIRONMENT!
Please stop here or only move on after you made a backup and kissed you loved ones.

you have to decide what is more important:
1. The actual version of waste collection schedule
or
2. The actual version of ICS calendar

If you decide for option one:
1. Delete and Uninstall the custom component ICS Calendar
2. Install, configure and start the addon "Advanced SSH & Web Terminal"
4. Switch to the addon and run `exec -it homeassistant /bin/sh` to connect to a shell of the homeassistant docker container.
5. Review the installed icalendar lib with `pip list | grep ical`, if icalendar is >=6.0.0 we need to uninstall it, if not - STOP and share the details here
6. Uninstall the libs with "pip uninstall icalendar icalevents" (icalevents needs to be uninstalled to make sure that we get the right version on restart)
7. Restart Home Assistant
8. WCS should work again
9. In case you need the ICS component, install it again but the max version should be 5.0.2...

if you decide for option two:
no change should be needed. WCS will not work.

**Comment by meilon** [comment]
I did it without removing anything:

1. Use HACS to downgrade ICS calendar to 5.0.3 (5.0.4 introduced the minimum icalendar 6.0.0)
2. uninstalled icalendar and icalevents as suggested
3. restarted Home Assistant

**Comment by Wilfried278** [comment]
If you decide for option one:

Use HACS to downgrade ICS calendar to 5.0.3 (5.0.4 introduced the minimum icalendar 6.0.0)
Install, configure and start the addon "Advanced SSH & Web Terminal"
Switch to the addon and run docker exec -it homeassistant /bin/sh to connect to a shell of the homeassistant docker container.
Review the installed icalendar lib with pip list | grep ical, if icalendar is >=6.0.0 we need to uninstall it, if not - STOP and share the details here
Uninstall the libs with pip uninstall icalendar icalevents (icalevents needs to be uninstalled to make sure that we get the right version on restart)
Restart Home Assistant

WCS don’t work !!!!!!!!!!

**Comment by ReneNulschDE** [comment]
> WCS don’t work !!!!!!!!!!

Hi @Wilfried278, what is not working and please explain your environment. Share the logs, share the output of the different steps. And please check your keyboard, looks like it is defect as it spawns exclamation marks...

**Comment by fsedarkalex** [comment]
had the same issue with abfall_io_ics (as it uses the same lib)

**Comment by Lateadapter** [comment]
same issue here with ics ... (ICS calendar 5.0.3 works)

**Comment by nuki47** [comment]
> 5\. pip uninstall icalendar icalevents

This way works for a downgrade, BUT after some restarts version 5.0.4 comes back and WCS don't work

**Comment by Lateadapter** [comment]
> > 5. pip uninstall icalendar icalevents
> 
> This way works for a downgrade, BUT after some restarts version 5.0.4 comes back and WCS don't work

To be honest, I'm not experienced enough to follow the SSH approach. I solved it by going back with full backup shortly after introducing HA Core 2024.10.3. That brought back beside a couple of other "old" versions also a working WCS (at this time the root cause of ICS was not clear for me, but already in consideration). Therefore I did start step by step to reinstall all the newer integrations. After each step I performed a full HA-backup, till finally ICS 5.0.4. was the only remaining integration. Everything else was working.
I performed a backup, installed ICS 5.0.4. and WCS disappeared - so far so known...
But now the idea was to solve the problem with the intentionally prepared "full backup". But BIG SURPRISE: Restoring the backup did NOT solve the issue! Obviously a "full backup" is not as "full" as expected.
So I went back to the beginning and stopped before ICS 5.0.4. ... which now I will ignore ...

**Comment by Wilfried278** [comment]
For me, these repairs with older versions are not an option. I prefer to wait until a new, stable and functioning update comes out. The frequency of WCS updates within 48 hours shows that several problems still need to be resolved. So I'm still waiting.Mit freundlichen GrüßenW.ZilgerAm 02.11.24 um 19:52 schrieb Lateadapter
                
            
            
                
                    Von: "Lateadapter" ***@***.***>Datum: 2. November 2024An: "mampfes/hacs_waste_collection_schedule" ***@***.***>Cc: "Wilfried" ***@***.***>,"Mention" ***@***.***>Betreff: Re: [mampfes/hacs_waste_collection_schedule] [Bug]: kwu_de source not found (Issue #2893)
                
                



pip uninstall icalendar icalevents


This way works for a downgrade, BUT after some restarts version 5.0.4 comes back and WCS don't work

To be honest, I'm not experienced enough to follow the SSH approach. I solved it by going back with full backup shortly after introducing HA Core 2024.10.3. That brought back beside a couple of other "old" versions also a working WCS (at this time the root cause of ICS was not clear for me, but already in consideration). Therefore I did start step by step to reinstall all the newer integrations. After each step I performed a full HA-backup, till finally ICS 5.0.4. was the only remaining integration. Everything else was working.
I performed a backup, installed ICS 5.0.4. and WCS disappeared - so far so known...
But now the idea was to solve the problem with the intentionally prepared "full backup". But BIG SURPRISE: Restoring the backup did NOT solve the issue! Obviously a "full backup" is not as "full" as expected.
So I went back to the beginning and stopped before ICS 5.0.4. ... which now I will ignore ...

**Comment by Wilfried278** [comment]
For me, these repairs with older versions are not an option. I prefer to wait until a new, stable and functioning update comes out. The frequency of WCS updates within 48 hours shows that several problems still need to be resolved. So I'm still waiting.

**Comment by smmmo** [comment]
I run home assistant in docker using ghcr.io/home-assistant/home-assistant:2024.11 and have the same problem because of ICS calendar.

The workaround of downgrading ICS calendar did not work for me. Even after I completely uninstalled ICS calendar, icalendar 6.0.1 was reinstalled after restarting ha. I couldn't find any other usage of icalendar, only in WCS. I've used this to search:
`grep -rnw './config/custom_components' -e 'icalendar'`

However, the fix for me was to first uninstall icalendar as suggested above:
`pip uninstall icalendar icalevents`
and then force the installation of 5.0.13 (the last version before 6.x) by modifying custom_components/waste_collection_schedule/manifest.json: 
`"requirements": ["icalendar==5.0.13", "recurring_ical_events", "icalevents>=0.1.26,!=0.1.28", "beautifulsoup4", "lxml", "pycryptodome"],`

I have no idea about Python, but maybe it's because WCS doesn't depend on any particular version of icalendar, so it always uses the latest version (if no other version is installed locally)?

**Comment by krajani786** [comment]
Hello, 

I have deleted ICS Calendar integration, and i don't have any ical stuff at all. I deleted WSC and every local calendar i have. Advanced SSH & Web Terminal does not work for me, never loads, i get a 504 error. Maybe because i have HA in proxmox and not a docker. I run Google Calendar integration as well. I have about 8 ICS orphaned Calendars that are tied to the waste collection schedule integration (although its not installed at the moment) these cannot be deleted no matter what i try. 
Everytime i try and add the WSC and choose my location i get unknown error. I do not know what logs you need or how to get them. please help.

**Comment by ReneNulschDE** [comment]
Please describe in detail how you have installed your HA environment and share the System Information (Settings, System, Repair - click on three dots in the upper left corner and share the system information)

We need the output of the command `pip list | grep ical` of the environment where your HA system is running.

**Comment by ReneNulschDE** [comment]
Now restart your HA environment. And check again. In case it is not working, share the relevant entries out of the homeassistant.log

**Comment by krajani786** [comment]
Hey, 

Thank you for your assistance. I did figure it out, simple enough i did not configure the add on properly. Although that did not fix the issue, i had no ical stuff installed. What i did, was the same thing someone mentioned above. I installed icalendar again, version 5.0.1 and did nothing with it. Then installed WSC again and it worked. This also got rid of all the ghost calendars.

**Comment by Marco4223** [comment]
Hi, question: is it now save to install the latest version (5.0.4) of the ICS calendar?

**Comment by Kanecaine** [comment]
So yet we have a short-term workaround. Many thanks to everyone who contributed to finding the cause in the ics-calendar component!
The current solution is to downgrade ics-calendar to version 5.0.3. Ok, but there was already 5.0.4 and 5.1.0. It can't be the solution to leave this component on the old version forever. The maintainer of ics-calendar does [not feel responsible](https://github.com/franc6/ics_calendar/issues/186#issuecomment-2542393045) for the fact that another component is disrupted by a dependency upgrade. For me as a user, this is quite understandable, because after all, the intention should always be to use up-to-date, bug-fixed and improved versions of a package. 

Accordingly, I assume that the solution must be found in WCS so that WCS is compatible with current versions of icalendar. But I admit that I am not familiar with all the technical backgrounds. I do wonder why the dependencies on other packages can lead to such problems. There seems to me to be a fundamental problem in the architecture, or in the way it is used.

Hence my question: can WCS be made compatible with the current version of icalendar or can the latest compatible version be used / referenced by WCS?

Alternatively, please coordinate with the maintainer of ics-calendar if the solution has to be found together.

Many thanks in advance!

**Comment by 5ila5** [comment]
The problem is, that we're using [icalevents](https://github.com/jazzband/icalevents) which makes it much easier to work with, especially for ICS files using reoccurring events. The best way to resolve this would be for the icalevents maintainer.
There already exists a pull request for this (https://github.com/jazzband/icalevents/pull/145) which looks like a pretty easy fix, but it does not look like there is any movement at the moment.

We could integrate ship icalevents with the changes within this repo (As both are MIT license it would be possible) but not my favorite approach

**Comment by mkrasselt1** [comment]
i didnt have ics calendar addon installed,
my ical version was 
```
/config # pip list | grep ical
ical                             8.2.0
icalendar                        6.1.0
icalevents                       0.1.29
recurring-ical-events            3.4.0
```

yet my waste collection addon shows all the "no ICAL" symptoms :/

**Comment by fsedarkalex** [comment]
@mkrasselt1 did you upgrade to HA 2025.1?

The waste collection schedule stopped working here either after upgrading. I did not yet check the logs for a reason but the calendar is gone.

**Comment by mkrasselt1** [comment]
@fsedarkalex
Yes i did, but i found installing latest version of ics calendar AND waste collection actualy slved the issue and i could readd my waste collection integration

**Comment by fsedarkalex** [comment]
so @mkrasselt1 you say that installing the breaking ICSCal version fixes WCS with HA 2025.1?

**Comment by fsedarkalex** [comment]
Tried it. 
ICS Calendar 5.1.0, HA 2025.1, WCS 2.5.0

Not working. Instead, the 500 error reappears.

**Comment by Jakob58** [comment]
I also tried it and have the same problem. WCS no longer runs since the update to HA 2025.1

**Comment by ReneNulschDE** [comment]
Please share the output of `pip list | grep ical` again. 

Whenever you run HA-OS, you need to connect to the HA-container first. (see [here](https://github.com/mampfes/hacs_waste_collection_schedule/issues/2893#issuecomment-2433200004), point 2 and 3)

**Comment by fsedarkalex** [comment]
I already tried to remove it and thus my results art probably not evidence. Still...
```
ical                             8.2.0
icalendar                        5.0.13
icalevents                       0.1.29
recurring-ical-events            3.4.0
```

Setup works (no 500) but get no calendar in the end.

**Comment by mkrasselt1** [comment]
> so @mkrasselt1 you say that installing the breaking ICSCal version fixes WCS with HA 2025.1?

For me it did:
I have ical sensor 1.7.1,trash card 2.4.5,ics calendar 5.1.0,week planner card 1.11.1

Installed and all working fine with homeassistant
 Core 2025.1.0
Supervisor 2024.12.3
Operating System 14.1
Frontend 20250103.0

**Comment by fsedarkalex** [comment]
> For me it did: I have ical sensor 1.7.1,trash card 2.4.5,ics calendar 5.1.0,week planner card 1.11.1

And which waste_collection_schedule version?


Maybe this log entry helps:

```
025-01-05 12:35:35.055 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ICS for waste_collection_schedule
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/init_ui.py", line 45, in async_setup_entry
    shell = await hass.async_add_executor_job(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 217, in create
    source_module: SourceModule = importlib.import_module(
                                  ~~~~~~~~~~~~~~~~~~~~~~~^
        f"waste_collection_schedule.source.{source_name}"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 16, in <module>
    from waste_collection_schedule.service.ICS_v1 import ICS_v1
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS_v1.py", line 6, in <module>
    import recurring_ical_events
  File "/usr/local/lib/python3.13/site-packages/recurring_ical_events.py", line 1530, in <module>
    class CalendarQuery:
    ...<193 lines>...
            raise IndexError("No components found.")
  File "/usr/local/lib/python3.13/site-packages/recurring_ical_events.py", line 1547, in CalendarQuery
    icalendar.InvalidCalendar,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'icalendar' has no attribute 'InvalidCalendar'
```

**Comment by Jakob58** [comment]
All affected modules are up to date:
HA 2025.01
ICS Calendar 5.1.0
WCS 2.5.0

The Logs: 

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:226
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 14:38:24 (1 Vorkommnisse)
Zuletzt protokolliert: 14:38:24

error loading source ics: No module named 'icalendar.windows_to_olson' Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 217, in create source_module: SourceModule = importlib.import_module( ~~~~~~~~~~~~~~~~~~~~~~~^ f"waste_collection_schedule.source.{source_name}" ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func return func(*args, **kwargs) File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module return _bootstrap._gcd_import(name[level:], package, level) ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen importlib._bootstrap>", line 1387, in _gcd_import File "<frozen importlib._bootstrap>", line 1360, in _find_and_load File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 935, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 1026, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 15, in <module> from waste_collection_schedule.service.ICS import ICS File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 7, in <module> from icalevents import icalevents File "/usr/local/lib/python3.13/site-packages/icalevents/icalevents.py", line 3, in <module> from .icalparser import parse_events, Event File "/usr/local/lib/python3.13/site-packages/icalevents/icalparser.py", line 18, in <module> from icalendar.windows_to_olson import WINDOWS_TO_OLSON ModuleNotFoundError: No module named 'icalendar.windows_to_olson'

————————————————

Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:366
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 14:38:30 (12 Vorkommnisse)
Zuletzt protokolliert: 14:38:30

Error while setting up waste_collection_schedule platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/waste_collection_schedule/sensor.py", line 147, in async_setup_platform
    raise ValueError(
        f"source_index {i} out of range (0-{len(api.shells) - 1}) please check your sensor configuration"
    )
ValueError: source_index 0 out of range (0--1) please check your sensor configuration

**Comment by ReneNulschDE** [comment]
@Jakob58 

> ICS Calendar 5.1.0

Please follow this [guide](https://github.com/mampfes/hacs_waste_collection_schedule/issues/2893#issuecomment-2433200004)

**Comment by BorgTen** [comment]
> @Jakob58
> 
> > ICS Calendar 5.1.0
> 
> Please follow this [guide](https://github.com/mampfes/hacs_waste_collection_schedule/issues/2893#issuecomment-2433200004)

This work-around did work for me with 2024.12, but not with 2025.1 anymore. After following the instructions of the work-around the following error occurs when booting:

`Logger: homeassistant.setup
Quelle: setup.py:416
Erstmals aufgetreten: 22:55:59 (1 Vorkommnisse)
Zuletzt protokolliert: 22:55:59

Error during setup of component waste_collection_schedule
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/init_yaml.py", line 109, in async_setup
    await hass.async_add_executor_job(
    ...<6 lines>...
    )
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/waste_collection_schedule/waste_collection_api.py", line 88, in add_source_shell
    new_shell = SourceShell.create(
        source_name=source_name,
    ...<3 lines>...
        day_offset=day_offset,
    )
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 217, in create
    source_module: SourceModule = importlib.import_module(
                                  ~~~~~~~~~~~~~~~~~~~~~~~^
        f"waste_collection_schedule.source.{source_name}"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 16, in <module>
    from waste_collection_schedule.service.ICS_v1 import ICS_v1
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS_v1.py", line 6, in <module>
    import recurring_ical_events
  File "/usr/local/lib/python3.13/site-packages/recurring_ical_events.py", line 1530, in <module>
    class CalendarQuery:
    ...<193 lines>...
            raise IndexError("No components found.")
  File "/usr/local/lib/python3.13/site-packages/recurring_ical_events.py", line 1547, in CalendarQuery
    icalendar.InvalidCalendar,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'icalendar' has no attribute 'InvalidCalendar'`

**Comment by Marco4223** [comment]
Its now a deadlock. If you update to 2025.1 the ICal Version 5.0.3 is no longer working and you need to update to 5.1.0. But with that version WCS is no longer working.

**Comment by bbr111** [comment]
@5ila5 I think this can be closed
