### ISSUE TITLE
[Bug]: bielefeld_de is not working

### ISSUE THREAD

**Issue by prokta85** [mampfes/hacs_waste_collection_schedule#2910]
### I Have A Problem With:

A specific source

### What's Your Problem

I like to setup waste collection schedule for "Bielefeld / bielefeld_de". I'm using the latest version of HA "2024.10.3" and waste_collection "2.3.0" and hit an issue during the setup. I've tried both ways "configuration.yaml" and via GUI. I pasted the logs below.
Right now I've no idea what the issue is or what I'm doing wrong during the setup.

Many thanks in advance

### Source (if relevant)

bielefeld_de

### Logs

```Shell
I see the following error in my logs:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:221
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 21:21:13 (1 Vorkommnisse)
Zuletzt protokolliert: 21:21:13

source not found: bielefeld_de
----
Logger: homeassistant.setup
Quelle: runner.py:189
Erstmals aufgetreten: 21:21:22 (1 Vorkommnisse)
Zuletzt protokolliert: 21:21:22

Setup of waste_collection_schedule is taking over 10 seconds.
----
Logger: homeassistant.util.loop
Quelle: util/loop.py:136
Erstmals aufgetreten: 21:30:51 (1 Vorkommnisse)
Zuletzt protokolliert: 21:30:51

Detected blocking call to open with args (PosixPath('/config/custom_components/waste_collection_schedule/sources.json'),) inside the event loop by custom integration 'waste_collection_schedule' at custom_components/waste_collection_schedule/config_flow.py, line 331: with p.open(encoding="utf-8") as json_file: (offender: /config/custom_components/waste_collection_schedule/config_flow.py, line 331: with p.open(encoding="utf-8") as json_file:), please report it to the author of the 'waste_collection_schedule' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 556, in start task = asyncio.Task(coro, loop=loop, eager_start=True) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle return await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post return await self._post_impl(request, data) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl return await super()._post_impl(request, data) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl result = await self._flow_mgr.async_init( File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1287, in async_init flow, result = await self._async_init(flow_id, handler, context, data) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1312, in _async_init flow = await self.async_create_flow(handler, context=context, data=data) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1505, in async_create_flow flow = handler() File "/config/custom_components/waste_collection_schedule/config_flow.py", line 306, in __init__ self._sources = self._get_source_list() File "/config/custom_components/waste_collection_schedule/config_flow.py", line 331, in _get_source_list with p.open(encoding="utf-8") as json_file:
```

### Relevant Configuration

```YAML
# waste_collection_schedule source configuration
waste_collection_schedule:
  sources:
    - name: bielefeld_de
      args:
        street: "Eckendorfer Straße"
        house_number: 57
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment]
What other custom components do you have installed? ics_calendar version 5.0.4? if yes, check [here](https://github.com/mampfes/hacs_waste_collection_schedule/issues/2893#issuecomment-2433200004)

**Comment by prokta85** [comment]
my ics_calender has version 5.04.
This is my pip list:
![image](https://github.com/user-attachments/assets/bc9f19d3-7cf0-4591-be3d-90c205b88d28)

**Comment by ReneNulschDE** [comment]
thx, then please move on [here](https://github.com/mampfes/hacs_waste_collection_schedule/issues/2893#issuecomment-2433200004)

your pip list is a liitle bit to short for a HA environment, maybe you are not in the right environment/docker/venv... please describe your setup or share the home assistant system info.

**Comment by prokta85** [comment]
@ReneNulschDE many thanks for your solution. I've deinstalled ics_calender and removed via pip the ics-* packages and after a restart it works, now.
