### ISSUE TITLE
[Bug]: "Biotonne" entry is missing for source "GFA Lüneburg"

### ISSUE THREAD

**Issue by fuchsbau123** [mampfes/hacs_waste_collection_schedule#2926]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

The entries for waste type "Biotonne" is missing for GFA Lüneburg source.

I can see the following types in the waste types of Waste Collection Schedule:
![image](https://github.com/user-attachments/assets/42b0dded-7cff-44c9-87f2-f57b7a31e1f5)
In the original calendar from GFA Lüneburg you can see the "Biotonne":
![image](https://github.com/user-attachments/assets/f0533bf8-f43a-4637-99b9-e949cf1174b2)

In the ICAL from GFA Lüneburg the  "Biotonne" is visible:
```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20241029
DTEND;VALUE=DATE:20241030
TRANSP:TRANSPARENT
X-MICROSOFT-CDO-BUSYSTATUS:FREE
LOCATION;LANGUAGE=de:XXXXX\, YYYYYYYYYYY
UID:1729973365258-48@portal.gfa-lueneburg.de:8443
DTSTAMP:20241026T100925Z
DESCRIPTION;LANGUAGE=de:
SUMMARY;LANGUAGE=de:Biotonne
PRIORITY:9
CLASS:PUBLIC
URL:https://www.gfa-lueneburg.de/
STATUS:CONFIRMED
END:VEVENT
```
Please help to add the "Biotonne" to the source GFA Lüneburg.

### Source (if relevant)

GFA Lüneburg

### Logs

```Shell
2024-10-26 21:26:04.183 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args (PosixPath('/config/custom_components/waste_collection_schedule/sources.json'),) inside the event loop by custom integration 'waste_collection_schedule' at custom_components/waste_collection_schedule/config_flow.py, line 331: with p.open(encoding="utf-8") as json_file: (offender: /config/custom_components/waste_collection_schedule/config_flow.py, line 331: with p.open(encoding="utf-8") as json_file:), please report it to the author of the 'waste_collection_schedule' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 556, in start
    task = asyncio.Task(coro, loop=loop, eager_start=True)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
    return await self._post_impl(request, data)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
    return await super()._post_impl(request, data)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1287, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1312, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1505, in async_create_flow
    flow = handler()
  File "/config/custom_components/waste_collection_schedule/config_flow.py", line 306, in __init__
    self._sources = self._get_source_list()
  File "/config/custom_components/waste_collection_schedule/config_flow.py", line 331, in _get_source_list
    with p.open(encoding="utf-8") as json_file:
```

### Relevant Configuration

```YAML
Home Assistant 2024.10.4 and Waste Collection Schedule 2.3.0
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment]
I can't reproduce this. My config:
![image](https://github.com/user-attachments/assets/c9b7e293-2578-438d-bde9-1c4b4715af97)

Result:
![image](https://github.com/user-attachments/assets/3f129e34-9911-4c52-9a2d-1da167c24194)

Please recheck and share your config in case it is not working.

**Comment by fuchsbau123** [comment]
> I can't reproduce this. My config: ![image](https://private-user-images.githubusercontent.com/33263735/381232183-c9b7e293-2578-438d-bde9-1c4b4715af97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMzIwNTksIm5iZiI6MTczMDIzMTc1OSwicGF0aCI6Ii8zMzI2MzczNS8zODEyMzIxODMtYzliN2UyOTMtMjU3OC00MzhkLWJkZTktMWM0YjQ3MTVhZjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE5NTU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhNWFkMTg0YmRlNmFkZDVkZGQxMmI2NzkyZjIzMTE5NDcyZTg0MTMzODNhNzU0ZjhkOTE0OThmNDdmMWQwNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PtVl-yUBV1k2MFP9Gl4EE40nnuE3U2aAct35GNIS6go)
> 
> Result: ![image](https://private-user-images.githubusercontent.com/33263735/381232478-3f129e34-9911-4c52-9a2d-1da167c24194.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMzIwNTksIm5iZiI6MTczMDIzMTc1OSwicGF0aCI6Ii8zMzI2MzczNS8zODEyMzI0NzgtM2YxMjllMzQtOTkxMS00YzUyLTlhMmQtMWRhMTY3YzI0MTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE5NTU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZDBkM2VkMGQ2NDUxNGRiYzM5YjBjYTJiZDZhZWZjOWIwNmI2YTZiNWM3ZTA3NTgwYjJmMDQzNDE4NDk2NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5eNBbpvJ1G3qnHPbVKDhtvxEq4aBKrXwzr-xVteZx-g)
> 
> Please recheck and share your config in case it is not working.

Hi Rene,
thanks for the answer. Here my config:
![image](https://github.com/user-attachments/assets/6486765b-6c67-4ad3-bbe1-5b36b91c21fc)

Here the data in the calendar:
Blue = Waste Collection Schedule
Yellow = ICS Calendar from GfA Lüneburg
![image](https://github.com/user-attachments/assets/8785ccfc-2d7a-4be7-a314-643d29bb7bce)

**Comment by fuchsbau123** [comment]
Hi Rene,
thanks for the answer. I was not able to send a comment without closing it. So I reopen it now...
Here my config:
![image](https://github.com/user-attachments/assets/6486765b-6c67-4ad3-bbe1-5b36b91c21fc)

Here the data in the calendar:
Blue = Waste Collection Schedule
Yellow = ICS Calendar from GfA Lüneburg
![image](https://github.com/user-attachments/assets/8785ccfc-2d7a-4be7-a314-643d29bb7bce)

**Comment by fuchsbau123** [comment]
Comment to re-open.

**Comment by ReneNulschDE** [comment]
@fuchsbau123 : I checked your address (Wandelfeld 1) and it does not show a biotonne in the web.
![image](https://github.com/user-attachments/assets/27d2267a-f462-4e94-9483-6e0f7fd29e06)

However, when I select Wandelfeld 3, I can see a Biotonne in the web but not in WCS. And the downloaded ics, shows the wrong address (Wandelfeld 1) - I have to analyze this. Looks like the house_number is not set correctly.

Please reopen the issue.
