### ISSUE TITLE
[Bug]: landkreis_rhoen_grabfeld broken because of removal of the .ical on the website

### ISSUE THREAD

**Issue by EinzellerXD** [mampfes/hacs_waste_collection_schedule#2968]
### I Have A Problem With:

A specific source

### What's Your Problem

The Source of landkreis_rhoen_grabfeld is broken because the .ical feature got removed from the website.
A Friend and I just noticed, that the entries form the HomeAssistant Calendar just disappeared, after updating the Integration/Rebooting HomeAssistant.

I already wrote an E-Mail to offizium.de, which is apparently in charge of the feature/website.

I hope they re add the feature..... Or at least some other source reliably covers this area.

### Source (if relevant)

landkreis_rhoen_grabfeld

### Logs

```Shell
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 20:59:37 (1 Vorkommnisse)
Zuletzt protokolliert: 20:59:37

fetch failed for source Landkreis Rhön Grabfeld: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/landkreis_rhoen_grabfeld.py", line 53, in fetch r.raise_for_status() File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 410 Client Error: Gone for url: https://fs-api-rg.offizium.com/abfalltermine?stadt=XXXXXX&ortsteil=XXXXXXXX
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by EinzellerXD** [comment]
Same as Issue #3006 
Will be fixed by #3015 

Closing this issue as "duplicate"
