### ISSUE TITLE
[Bug]: muellmax.de Got invalid response from the server, please recheck your arguments

### ISSUE THREAD

**Issue by lolmeister77** [mampfes/hacs_waste_collection_schedule#3014]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

Since yesterday i get these errors. I'm not sure if something has change on my configuration.

### Logs

```Shell
fetch failed for source Müllmax: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/icalendar/parser.py", line 339, in parts validate_token(name) File "/usr/local/lib/python3.12/site-packages/icalendar/parser.py", line 128, in validate_token raise ValueError(name) ValueError: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/muellmax_de.py", line 165, in fetch dates = self._ics.convert(r.text) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, in convert events: List[Any] = icalevents.events( ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( ^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/icalevents/icalparser.py", line 299, in parse_events calendar = Calendar.from_ical(content) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/icalendar/cal.py", line 331, in from_ical name, params, vals = line.parts() ^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/icalendar/parser.py", line 353, in parts raise ValueError( ValueError: Content line could not be parsed into parts: '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">': <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/muellmax_de.py", line 167, in fetch raise ValueError( ValueError: Got invalid response from the server, please recheck your arguments
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by lolmeister77** [comment]
Switching to a locally stored ical File works

**Comment by lolmeister77** [comment]
ok i think something change on the müllmax side because everything works again.

**Comment by lolmeister77** [comment]
ok i think something change on the müllmax side because everything works again.

**Comment by lolmeister77** [comment]
some additional information. I think i got blacklistetd by müllmax:

> Das Abfragelimit wurde überschritten!
> 
> Deshalb wurde Ihr Zugang zur Datenbank für 24 Stunden deaktiviert.
> 
>  
> Wie kann das passieren?
> 
> Müllmax stellt die Abfuhrdaten für die persönliche Nutzung mit einem Internet Browser zur Verfügung. Das Abfragelimit wird erst überschritten, wenn wesentlich mehr als die zu erwartenden Zugriffe für den privaten Gebrauch stattfinden. Dann wird der Zugang, auch zum Schutz vor Hackerangriffen, deaktiviert.
> 
>  
> Script-Zugriffe durch Smart Home Systeme
> 
> Wenn Zugriffe von Menschen alternativ durch Scripte ersetzt werden, kann das sehr sinnvoll sein. Wir stellen jedoch fest, dass Scripte häufig nicht bestimmungsgemäß verwendet werden, um überwiegend iCalender bis zu 60x pro Minute anzufordern. Grundsätzlich unterstützen wir auch mehrere Abfragen am Tag. Sogenanntes Polling, das immer das gleiche Ergebnis liefert, führt hingegen zur Deaktivierung.
>  
> Wenn wir Abfuhrdaten aktualisieren, ist die Änderung für den Tag der Aktualisierung nicht relevant. Dann ist die Abfuhr auch bereits unterwegs. Änderungen erfolgen während der Arbeitszeit, in der Regel zwischen 06:00 und 18:00 Uhr. Deshalb ist es vollkommen ausreichend, einmal täglich außerhalb dieses Zeitraumes einen iCalender anzufordern.
>
