### ISSUE TITLE
Calendar Error after 1.24.0 Update

### ISSUE THREAD

**Issue by VDRainer** [mampfes/hacs_waste_collection_schedule#316]
```txt
2022-07-31 12:19:17 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.waste_collection_schedule.calendar
Traceback (most recent call last):
  File "/srv/ha/lib/python3.9/site-packages/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/ha/lib/python3.9/site-packages/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassi/.homeassistant/custom_components/waste_collection_schedule/calendar.py", line 118, in <module>
    def calc_unique_calendar_id(scraper: Scraper, type: str | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
2022-07-31 12:19:17 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform waste_collection_schedule.calendar: Platform not found (Exception importing custom_components.waste_collection_schedule.calendar).
```

**Comment by mampfes** [comment]
Please add your configuration and context information.

**Comment by VDRainer** [comment]
```
waste_collection_schedule:
  sources:
    - name: abfall_io
      args:
        key: 3701fd1ff111f63996ab46a448669ea3
        f_id_kommune: 1069
        f_id_bezirk: 979
        f_id_strasse: 2890

sensor:
  - platform: waste_collection_schedule
    source_index: 0
    name: Abfall WaBue
    details_format: "appointment_types"
    date_template: '{{value.types|default|join(", ")}}|{{value.daysTo}}|{{value.date.strftime("%d.%m.%Y")}}|{{value.date.strftime("%a")}}'
```
![20220731_205522](https://user-images.githubusercontent.com/26381449/182041233-5664e3e7-dac7-4ea5-a40f-f95336c409ae.png)
Calendar, which is available in 1.23.0, 
![20220731_205704](https://user-images.githubusercontent.com/26381449/182041256-430b1189-5e9b-4ba9-94c4-9bbf27de0f91.png)
is unavailable 1.24.0
![20220731_210149](https://user-images.githubusercontent.com/26381449/182041304-a4f8a6a7-c8d6-4376-b811-fd37017000de.png)

**Comment by maxxam4** [comment]
I get the same error. Although I don't use the calendar entry, I have the identical messages in the log. The other sensors work.

```yml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        #url: "https://apm.wastebox.gemos-management.de/Gemos/WasteBox/Frontend/TourSchedule/Raw/Name/2022/year/154442/1416,1418,1420/Print/ics/Default/Abfuhrtermine.ics"
        file: "/home/homeassistant/.homeassistant/www/Abfuhrtermine.ics"
        offset: 0
      customize:
        - type: Restabfall 40 l bis 240 l
          alias: Restmüll
          icon: mdi:trash-can-outline
        - type: Papiertonne 240 l
          alias: Papiertonne
          icon: mdi:newspaper-variant-multiple-outline
        - type: Gelbe Tonne
          alias: Gelbe Tonne
          icon: mdi:recycle
        - type: Papiertonne; Restmüll
          alias: Papiertonne, Restmüll
          icon: mdi:truck-outline
      calendar_title: Müllabfuhr

sensor:
  - platform: waste_collection_schedule
    name: waste_collection_waste
    details_format: upcoming
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Restmüll

```
```txt
2022-08-01 22:53:17 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.waste_collection_schedule.calendar
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/waste_collection_schedule/calendar.py", line 118, in <module>
    def calc_unique_calendar_id(scraper: Scraper, type: str | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
2022-08-01 22:53:17 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform waste_collection_schedule.calendar: Platform not found (Exception importing custom_components.waste_collection_schedule.calendar).

**Comment by luebbe** [comment]
Same here:
```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.loader
Source: custom_components/waste_collection_schedule/calendar.py:118
Integration: waste_collection_schedule (documentation)
First occurred: 08:46:02 (1 occurrences)
Last logged: 08:46:02

Unexpected exception importing platform custom_components.waste_collection_schedule.calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/waste_collection_schedule/calendar.py", line 118, in <module>
    def calc_unique_calendar_id(scraper: Scraper, type: str | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

configuration.yaml
```yaml
################################################
## Müllabführ
################################################

waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: !secret waste_url
      customize:
        - type: Restabfallbehaelter
          alias: Restmülltonne
          icon: mdi:trash-can
        - type: Wertstoffbehaelter
          alias: Wertstofftonne
          icon: mdi:recycle
        - type: Biobehaelter
          alias: Biotonne
          icon: mdi:flower-outline

```

sensors.yaml
```yaml
################################################
## Müllabfuhr
################################################

- platform: waste_collection_schedule
  name: Müllabfuhr
  value_template: '{{value.types|join(", ")}}|{{value.daysTo}}|{{value.date.strftime("%d.%m.%Y")}}|{{value.date.strftime("%a")}}'
  types:
    - Biotonne
    - Restmülltonne
    - Wertstofftonne

```

**Comment by tastymeatball** [comment]
Changing line 118 from
def calc_unique_calendar_id(scraper: Scraper, type: str | None = None):
to
def calc_unique_calendar_id(scraper: Scraper, type: str = None):
fixes the problem for me

**Comment by VDRainer** [comment]
> def calc_unique_calendar_id(scraper: Scraper, type: str = None):

Thanks, for my too.
This code is from PR https://github.com/mampfes/hacs_waste_collection_schedule/pull/287
Is this a bug or something that needs to be configured additionally?

**Comment by mampfes** [comment]
In Python 3.10, `str | None` is a valid syntax. As Home Assistant alread switched to 3.10 with release 2022.7, I would like to leave it as it is.

**Comment by VDRainer** [comment]
Thanks for that explanation.  :+1: 
With the fix from @tastymeatball, this issue can be closed for me.

**Comment by prageeth** [comment]
Hi @mampfes, thanks for the explanation. I understand that HA is already on 3.10, but there are lots of people still running older versions of python, especially when running HA Core. It would be good to have a non-breaking version (backward compatibility). Wdyt?

**Comment by luebbe** [comment]
Thanks for the info. I was still on HA 2022.6 in Docker. Upgraded to 2022.8 and now everything is fine. I'm glad I got out of Python version hell by switching to HA Docker a year or two ago.
