### ISSUE TITLE
[Bug]: ics url not found

### ISSUE THREAD

**Issue by VolkerMal** [mampfes/hacs_waste_collection_schedule#3223]
### I Have A Problem With:

A specific source

### What's Your Problem

my integration does not receive any data any longer and HA logs report the following error (see below)

### Logs

```Shell
2024-12-16 21:32:37.295 ERROR (SyncWorker_2) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Abfallwirtschaftsbetrieb Esslingen:
Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch
    entries: Iterable[Collection] = self._source.fetch()
                                    ~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/awb_es_de.py", line 47, in fetch
    raise Exception("ics url not found")
Exception: ics url not found
```

### Relevant Configuration

```YAML
past taken from configuration.yaml

waste_collection_schedule:
  sources:
    - name: awb_es_de
      args:
        city: Ostfildern
        street: Schwabstrasse
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by VolkerMal** [comment]
it sounds similar to #3108 but its not different.
yes, AWB seems to have changes the strings of the street by adding "Alle Hausnummern" in case there is no differentiation within one street.
by any syntax I am trying does not resolve the issue.
old value:   Schwabstrasse
new result by AWB ES: Schwabstraße Alle Hausnummern
but if you choose:
Schwabstraße Alle Hausnummern
   or
Schwabstrasse Alle Hausnummern

the result is both negative - no data retrieved

**Comment by VolkerMal** [comment]
issue is fixed.
during my tests HA did created multiple new entity ID's for the HACS integration.
Due to the fact I did not updated them in my calendar, I did not realized having the issue fixed already  stupid me.
Case closed
