### ISSUE TITLE
Kingston.gov.uk appears to have changed date formats again

### ISSUE THREAD

**Issue by cmsj** [mampfes/hacs_waste_collection_schedule#3224]
@ilbarone87 I think they might have changed something again, I'm now seeing:

```
2024-12-16 09:47:12.097 ERROR (SyncWorker_8) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source The Royal Borough of Kingston Council:
Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch
    entries: Iterable[Collection] = self._source.fetch()
                                    ~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/kingston_gov_uk.py", line 79, in fetch
    date=datetime.strptime(
         ~~~~~~~~~~~~~~~~~^
        data["echo_refuse_next_date"], "%Y/%m/%d %H:%M:%S"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ).date(),
    ^
  File "/usr/local/lib/python3.13/_strptime.py", line 573, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/_strptime.py", line 352, in _strptime
    raise ValueError("time data %r does not match format %r" %
                     (data_string, format))
ValueError: time data 'Friday 20 December' does not match format '%Y/%m/%d %H:%M:%S'
```

_Originally posted by @cmsj in https://github.com/mampfes/hacs_waste_collection_schedule/issues/3078#issuecomment-2545096194_

**Comment by cmsj** [comment]
I added some debugging (e.g. `_LOGGER.warning(f"refuse: {data["echo_refuse_next_date"]}")`) to each of the `Collection()` creations to print the date string being extracted, and it seems like there is data for each collection type:

```
2024-12-17 00:52:11.140 WARNING (SyncWorker_0) [waste_collection_schedule.source.kingston_gov_uk] refuse: Friday 20 December
2024-12-17 00:52:11.140 WARNING (SyncWorker_0) [waste_collection_schedule.source.kingston_gov_uk] food: Friday 20 December
2024-12-17 00:52:11.140 WARNING (SyncWorker_0) [waste_collection_schedule.source.kingston_gov_uk] papercard: Friday 20 December
2024-12-17 00:52:11.140 WARNING (SyncWorker_0) [waste_collection_schedule.source.kingston_gov_uk] mixed: Monday 30 December
```

There's nothing showing up in the calendar though.

**Comment by cmsj** [comment]
@ilbarone87 I'm seeing the same thing you did here: https://github.com/mampfes/hacs_waste_collection_schedule/issues/3078#issuecomment-2547119089

**Comment by cmsj** [comment]
Filed https://github.com/mampfes/hacs_waste_collection_schedule/pull/3225

**Comment by ilbarone87** [comment]
Amazing work @cmsj thank you!

**Comment by the-jeffski** [comment]
Wonder if we are better having some try loop in case they revert again to a previous format?

**Comment by elyobelyob** [comment]
Thanks for the fix, have manually updated my system. Would definitely recommend handling both actual year as well as 1900. With the time it is taking to get the PR in, and that the 1900 year may be an error, it'd be painful to have to go through the PR process again.

**Comment by excitron** [comment]
Still getting this issue with 2.6.0 ![image](https://github.com/user-attachments/assets/f350db46-e0b1-4daa-9cde-b8428a54c2b0)

**Comment by ilbarone87** [comment]
@excitron PR hasn't been merged still. There is some work to complete.
