### ISSUE TITLE
[Bug]: Poznań, Poland source not working

### ISSUE THREAD

**Issue by peyn** [mampfes/hacs_waste_collection_schedule#3236]
### I Have A Problem With:

A specific source

### What's Your Problem

Hi,

Since the beginning of December the source for Poznań (Poland) stopped working.
They must have changed something on the source page, because the error I see in Home Assistant is as shown in the log.

Looks like before the table with the dates was different, maybe had one month per row (?), I don't know.
But now it shows only one month with different garbage times per row, which causes an issue, because February (second row) cannot have more than 29 days. :-)

![image](https://github.com/user-attachments/assets/0d4c42ff-5fbb-4742-992c-95964e0d326d)

Kind regards,
Mateusz

### Source (if relevant)

poznan_pl

### Logs

```Shell
2024-12-18 20:48:04.688 ERROR (SyncWorker_8) [custom_components.waste_collection_schedule.waste_collection_schedule.source_shell] fetch failed for source Poznań:
Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch
    entries: Iterable[Collection] = self._source.fetch()
                                    ~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/poznan_pl.py", line 87, in fetch
    datetime.date(year, row_index, int(day)),
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: day is out of range for month
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by peyn** [comment]
Duplicate of #3183
