### ISSUE TITLE
[Bug]: Error AppAbfallplusDe.py - no data

### ISSUE THREAD

**Issue by threadstone83** [mampfes/hacs_waste_collection_schedule#3245]
### I Have A Problem With:

A specific source

### What's Your Problem

Since today I don't get values for my waste collection schedule. I use AppAbfallplusDe.py (Landkreis Bad Kissingen -> Nüdlingen). I don't have changed anything.

### Source (if relevant)

AppAbfallplusDe.py

### Logs

```Shell
Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 22:28:58 (1 Vorkommnisse)
Zuletzt protokolliert: 22:28:58

fetch failed for source Apps by Abfall+: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py", line 183, in fetch for d in self._app.generate_calendar(): ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 990, in generate_calendar self.select_kommune() ~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 661, in select_kommune raise SourceArgumentNotFound( "city", self._region_search, [r["name"] for r in regions] ) waste_collection_schedule.exceptions.SourceArgumentNotFound: We could not find values for the argument 'city' with the value 'Nüdlingen'
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by threadstone83** [comment]
False alert - after two restarts all works again. Sorry for disturbing!
