### ISSUE TITLE
[Bug]: Fetch failed for source Odense Renovation

### ISSUE THREAD

**Issue by yoali11** [mampfes/hacs_waste_collection_schedule#3254]
### I Have A Problem With:

A specific source

### What's Your Problem

It seems like the API endpoint for Odense Renovation has changed, since the API endpoint used by this integration does not work anymore.

### Logs

```Shell
This error originated from a custom integration.

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
integration: Waste Collection Schedule (documentation)
First occurred: 20 December 2024 at 15:24:21 (2 occurrences)
Last logged: 01:04:59

fetch failed for source Odense Renovation: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/odenserenovation_dk.py", line 44, in fetch response.raise_for_status() ~~~~~~~~~~~~~~~~~~~~~~~~~^^ File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mit.odenserenovation.dk/api/Calendar/GetCalendarByAddress?addressNo=XXXXXX&startDate=2024-12-20T15%3A24%3A21.571789&endDate=2025-12-20T15%3A24%3A21.571793&noCache=False
fetch failed for source Odense Renovation: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/odenserenovation_dk.py", line 44, in fetch response.raise_for_status() ~~~~~~~~~~~~~~~~~~~~~~~~~^^ File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mit.odenserenovation.dk/api/Calendar/GetCalendarByAddress?addressNo=XXXXXX&startDate=2024-12-21T01%3A04%3A59.354880&endDate=2025-12-21T01%3A04%3A59.354885&noCache=False
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by bthorsted** [comment]
Did you hear back from Odense Renovation? As far as I can tell, the URL looks to be correct, but the request sent from their own website also has query parameter named "key" and the start and end date have a postfixed "Z".

**Comment by avzdk** [comment]
Still not working. 

WHen I follow instructions on odenserenovation to get link I get a link like this.
https://mit.odenserenovation.dk/api/Calendar/GetICalCalendar?addressNo=12345678

The waste add-on try to fetch data from another endpoint.
https://mit.odenserenovation.dk/api/Calendar/GetCalendarByAddress?addressNo=153832
&startDate=2025-12-02T15%3A52%3A35.791727&endDate=2026-12-02T15%3A52%3A35.791730&noCache=False

**Comment by mbendtsen** [comment]
Looks like you need to call `POST https://mit.odenserenovation.dk/api/Calendar/GetCalendarByAddress?addressNo=151357&endDate=2027-12-30T23%3A00%3A00.000Z&noCache=false&key=EAAAACQaTdPiPLLXJo3TlsP%2B32udYHiinSEP%2Bwwn6i6gR3yKztHQkC0c8sCWLiVAyiVS%2Fg%3D%3D&startDate=2026-01-14T21%3A34%3A35.967Z`

But the problem could be with the `key` and the cookie that they added. It looks like an asp,net session cookie.

**Comment by bthorsted** [comment]
What is the issue with the key and asp.net session cookie? Is it not possible to handle it programmatically?

**Comment by bbr111** [comment]
Thanks everyone for the detailed digging on this — I went and looked at the current mit.odenserenovation.dk widget code directly to pin down exactly what changed.

The relevant part of their current JS bundle (`mitors-bundle.min.js`) builds the calendar request like this:

    n.set("key", this.calendarKey);
    ...
    grecaptcha.execute("6Le4wwYoAAAAACoyQQHM6Ac6ZQZj3rzaoCraaOa2", {action: "submit"}).then(e => {
      $.ajax({
        url: n,               // same URL incl. addressNo/startDate/endDate/key
        type: "Post",
        contentType: "application/json",
        data: JSON.stringify({ token: e })
      });
    });

So the endpoint isn't just at a different path — it now:
1. Requires a **POST**, not a GET.
2. Requires a Google **reCAPTCHA v3 token** in the JSON body, freshly minted by `grecaptcha.execute(...)` for their registered site key.
3. Requires a `key` value that only ever gets rendered into the page server-side (tied to the ASP.NET session cookie set when you load the page), matching what @mbendtsen found.

I also checked the `GetICalCalendar` link mentioned above — it no longer exists in the current widget code and returns a 500 when called directly, so it looks like a leftover/removed endpoint rather than a working bypass.

Given Odense Renovation's own reply that they've added security measures and are "looking at how and to what extent" they'll expose data going forward, this looks like a deliberate anti-scraping change rather than a bug on their infrastructure. A reCAPTCHA v3 token can only be legitimately produced by Google's JS running in a real browser against their site key — there's no way for this integration to generate one from a plain HTTP request, and building something that tries to defeat that check isn't something this project does (same principle we apply to login-required sources).

Practically, this means the `odenserenovation_dk` source can't be repaired with a code change right now. If Odense Renovation reopens a public, unauthenticated endpoint (or publishes an official public API/ICS feed), we'll happily wire it up.

I'm closing this issue since there's no actionable code fix available right now, but please feel free to reopen this issue (or file a new one) if the provider changes something and a public endpoint becomes available again.
