### ISSUE TITLE
[Bug]: Abfall Havelland stopped working

### ISSUE THREAD

**Issue by adieball** [mampfes/hacs_waste_collection_schedule#3266]
### I Have A Problem With:

A specific source

### What's Your Problem

ABH not working anymore, complaining about missing ICS file.
Worked fine quite some time. Running 2.5.0 

### Source (if relevant)

Abfall Havelland

### Logs

```Shell
Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
Integration: Waste Collection Schedule ([Dokumentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
Erstmals aufgetreten: 22. Dezember 2024 um 13:18:42 (2 Vorkommnisse)
Zuletzt protokolliert: 01:37:13

fetch failed for source Abfallbehandlungsgesellschaft Havelland mbH (abh): Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/abfall_havelland_de.py", line 46, in fetch raise Exception("No ics link found") Exception: No ics link found
```

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: abfall_havelland_de
      args:
        ort: Wustermark OT Elstal
        strasse: Glockenheidering
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
fixed in #3392

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
