### ISSUE TITLE
[Bug]: Integration can't load - showing invalid config

### ISSUE THREAD

**Issue by ChristophCaina** [mampfes/hacs_waste_collection_schedule#3271]
### I Have A Problem With:

The integration in general

### What's Your Problem

Since today, the integration is showing an invalid configuration in HomeAssistant - and won't load anymore.

### Logs

```Shell
Logger: homeassistant.setup
Source: setup.py:416
First occurred: 11:39:24 AM (1 occurrences)
Last logged: 11:39:24 AM

Error during setup of component waste_collection_schedule
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/init_yaml.py", line 109, in async_setup
    await hass.async_add_executor_job(
    ...<6 lines>...
    )
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/waste_collection_schedule/waste_collection_api.py", line 88, in add_source_shell
    new_shell = SourceShell.create(
        source_name=source_name,
    ...<3 lines>...
        day_offset=day_offset,
    )
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 217, in create
    source_module: SourceModule = importlib.import_module(
                                  ~~~~~~~~~~~~~~~~~~~~~~~^
        f"waste_collection_schedule.source.{source_name}"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 16, in <module>
    from waste_collection_schedule.service.ICS_v1 import ICS_v1
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS_v1.py", line 6, in <module>
    import recurring_ical_events
  File "/usr/local/lib/python3.13/site-packages/recurring_ical_events.py", line 1530, in <module>
    class CalendarQuery:
    ...<193 lines>...
            raise IndexError("No components found.")
  File "/usr/local/lib/python3.13/site-packages/recurring_ical_events.py", line 1547, in CalendarQuery
    icalendar.InvalidCalendar,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'icalendar' has no attribute 'InvalidCalendar'
```

### Relevant Configuration

```YAML
[configuration.yaml]
waste_collection_schedule: !include waste_collection_scheduler.yaml


[waste_collection_scheduler.yaml]
  sources:
    - name: ics
      args:
        url: https://api.abfall.io/?key=76bdaac8568082d77e7a90cb41129f9b&mode=export&idhousenumber=1083&wastetypes=50,53,299,31&timeperiod={%Y}0101-{%Y}1231&showinactive=false&type=ics
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by Gloomyeye** [comment]
I can confirm that this bug is introduced with the newest 2025.1 beta version.

**Comment by samuel9554** [comment]
I also have this bug in 2025.1 beta.

**Comment by hessel-a** [comment]
Could it be that Python version 3.13 is the sources of th error. https://rc.home-assistant.io/blog/2024/12/04/release-202412/#weve-upgraded-to-python-313

**Comment by itsdoublearon** [comment]
Can confirm this bug is happening to me as well, on 2024.12.5

**Comment by nobbilie** [comment]
Unfortunately, I also have this problem with the new beta 2025.01

**Comment by schmidtfx** [comment]
Is someone looking into this already?

**Comment by andreasbrett** [comment]
Waste Collection Schedule has problematic dependencies:

1) recurring-ical-events v3.4.0 (released Dec 20th 2024)
 - https://pypi.org/project/recurring-ical-events/
 - https://github.com/niccokunzmann/python-recurring-ical-events
 - requires: 6.1.0 <= icalendar < 7.0.0

2) icalevents v0.1.29 (released Sep 9th 2024)
- https://pypi.org/project/icalevents/
- https://github.com/jazzband/icalevents
- requires fixed version of icalendar 5.0.13

Until icalevents does change its requirements, WCS will not work unless it gets rid of icalevents.

**Comment by udochrist** [comment]
Updated to HA 2025.1 and am now getting the error...

**Comment by hessel-a** [comment]
#3394

**Comment by z-master42** [comment]
See https://github.com/mampfes/hacs_waste_collection_schedule/issues/3390#issuecomment-2571401640

**Comment by ChristophCaina** [comment]
Fixed with the linked pr.
Thanks :)

**Comment by kwithus** [comment]
> Fixed with the linked pr. Thanks :)

can somebody give a detailed instructions how to fix?

**Comment by MTK0815** [comment]
Quick fix (at your own risk, but works perfectly):

    Go to “custom_components > waste_collection_schedule > waste_collection_schedule > service”
    Delete “ICS_v1.py”
    Go to “custom_components > waste_collection_schedule > waste_collection_schedule > source > ics.py”
    Comment out line 16 (“from waste_collection_schedule.service.ICS_v1 import ICS_v1”) with #.
    Comment out lines 154 to 160 ( “if version ==1” up to “)” ) with #.
    Enjoy!

**Comment by z-master42** [comment]
The else must also be removed.Only the content of the else must remain, but the indentation must be adjusted. See PR.

**Comment by MTK0815** [comment]
I didn't delete the else. Everything works for me

**Comment by MelleD** [comment]
@z-master42 thanks will try that too.
Do you plan to create a PR?

**Comment by z-master42** [comment]
> I didn't delete the else. Everything works for me 

That's luck.

**Comment by z-master42** [comment]
> @z-master42 thanks will try that too.
> Do you plan to create a PR?

There is: #3421.  But the more advanced and forward-thinking version is #3468.

**Comment by MelleD** [comment]
> > @z-master42 thanks will try that too.
> > Do you plan to create a PR?
> 
> There is: #3421. But the more advanced and forward-thinking version is #3468.

Thanks works, but have to reconfigure everything

**Comment by itsdoublearon** [comment]
Did the manual edit and that worked, but updated to 2.6.0 and it's broken again ☹️

**Comment by kwithus** [comment]
Same here (Germany/Zweckverband Region Hannover (AHA)

**Comment by darth-hp** [comment]
2.6.0 works for Böblingen api.abfall.io

**Comment by lomtaslipptas** [comment]
2.6.0 works for Google Calendar
