### ISSUE TITLE
[Bug]: Service Provider "Abfalltermine Forchheim" No Longer Works

### ISSUE THREAD

**Issue by johannesalt** [mampfes/hacs_waste_collection_schedule#3341]
### I Have A Problem With:

A specific source

### What's Your Problem

The service provider "Abfalltermine Forchheim" is no longer functioning as expected. When attempting to download the .ics file (which provides the waste collection schedule), the request does not complete successfully. It appears that the system for downloading the .ics file no longer supports **HTTP**. Although the download via **HTTPS** works as expected, the HTTP method fails to retrieve the .ics file.

### Source (if relevant)

abfalltermine_forchheim_de

### Logs

```Shell
error loading source abfalltermine_forchheim_de: No module named 'icalevents' Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 217, in create source_module: SourceModule = importlib.import_module( ~~~~~~~~~~~~~~~~~~~~~~~^ f"waste_collection_schedule.source.{source_name}" ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func return func(*args, **kwargs) File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module return _bootstrap._gcd_import(name[level:], package, level) ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen importlib._bootstrap>", line 1387, in _gcd_import File "<frozen importlib._bootstrap>", line 1360, in _find_and_load File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 935, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 1022, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/abfalltermine_forchheim_de.py", line 5, in <module> from waste_collection_schedule.service.ICS import ICS File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 7, in <module> from icalevents import icalevents ModuleNotFoundError: No module named 'icalevents'
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by markvp** [comment]
Thanks for the report! There are two things happening here:

**1. HTTP → HTTPS:** The provider now redirects all HTTP requests to HTTPS. A one-line fix to update the URL scheme in the source takes care of this — I've prepared a PR for it.

**2. `No module named 'icalevents'`:** This is a stale installation issue rather than a bug in the code. The `icalevents` library has been listed in the integration's `manifest.json` requirements for a long time, so HA should install it automatically. The most reliable fix is to go to HACS → Waste Collection Schedule → the three-dot menu → **Redownload** and select the **master** branch. That forces HACS to reinstall all dependencies cleanly. After restarting Home Assistant the error should be gone.
