### ISSUE TITLE
Issue to get the date for Recycle! / RecycleApp.be

### ISSUE THREAD

**Issue by Gunth** [mampfes/hacs_waste_collection_schedule#407]
Hi all,

Since today i have an issue when getting the dates for this service providers Recycle! / RecycleApp.be.

Here is the logs :

```
2022-10-24 15:28:18.281 ERROR (SyncWorker_4) [waste_collection_schedule.scraper] fetch failed for source Recycle!:
Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", line 141, in fetch
    entries = self._source.fetch()
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/recycleapp_be.py", line 54, in fetch
    headers["Authorization"] = r.json()["accessToken"]
KeyError: 'accessToken'
```

Version : 1.28.0

**Comment by dt215git** [comment]
Looks like the API address has changed, the x-secret parameter is now different, and a POST is needed in one step rather than a GET.
I get this response have changed a few things in the recycleapp_be.py file, but don't know how it compares to what it used to produce - 366 results for one address seems a bit odd, but maybe they genuinely get a collection every few days.

```
Testing source recycleapp_be ...
  found 366 entries for 1140 Evere, Bazellaan 1
    2022-10-25: Household waste [None]
    2022-10-25: PMD [None]
    2022-10-28: Food waste [None]
    2022-10-28: Pruning waste [None]
    2022-10-28: Green waste [None]
    2022-10-28: Household waste [None]
    2022-10-28: Paper-cardboard [None]
    2022-11-01: Household waste [None]
    2022-11-01: PMD [None]
    2022-11-04: Food waste [None]
    2022-11-04: Pruning waste [None]
    2022-11-04: Green waste [None]
    2022-11-04: Household waste [None]
    2022-11-04: Paper-cardboard [None]
    2022-11-08: Household waste [None]
    2022-11-08: PMD [None]
    2022-11-11: Food waste [None]
    2022-11-11: Pruning waste [None]
    2022-11-11: Green waste [None]
    2022-11-11: Household waste [None]
    2022-11-11: Paper-cardboard [None]
    2022-11-15: Household waste [None]
    2022-11-15: PMD [None]
    2022-11-18: Food waste [None]
    2022-11-18: Pruning waste [None]
    2022-11-18: Green waste [None]
    2022-11-18: Household waste [None]
    2022-11-18: Paper-cardboard [None]
    2022-11-22: Household waste [None]
    2022-11-22: PMD [None]
    2022-11-25: Food waste [None]
    2022-11-25: Pruning waste [None]
    2022-11-25: Green waste [None]
    2022-11-25: Household waste [None]
    2022-11-25: Paper-cardboard [None]
    2022-11-29: Household waste [None]
    2022-11-29: PMD [None]
    2022-12-02: Food waste [None]
    2022-12-02: Pruning waste [None]
    2022-12-02: Green waste [None]
    2022-12-02: Household waste [None]
    2022-12-02: Paper-cardboard [None]
    2022-12-06: Household waste [None]
    2022-12-06: PMD [None]
    2022-12-09: Food waste [None]
    2022-12-09: Pruning waste [None]
    2022-12-09: Green waste [None]
    2022-12-09: Household waste [None]
    2022-12-09: Paper-cardboard [None]
    2022-12-13: Household waste [None]
    2022-12-13: PMD [None]
    2022-12-16: Food waste [None]
    2022-12-16: Pruning waste [None]
    2022-12-16: Green waste [None]
    2022-12-16: Household waste [None]
    2022-12-16: Paper-cardboard [None]
    2022-12-20: Household waste [None]
    2022-12-20: PMD [None]
    2022-12-23: Food waste [None]
    2022-12-23: Pruning waste [None]
    2022-12-23: Green waste [None]
    2022-12-23: Household waste [None]
    2022-12-23: Paper-cardboard [None]
    2022-12-27: Household waste [None]
    2022-12-27: PMD [None]
    2022-12-30: Food waste [None]
    2022-12-30: Pruning waste [None]
    2022-12-30: Green waste [None]
    2022-12-30: Household waste [None]
    2022-12-30: Paper-cardboard [None]
    2023-01-03: Household waste [None]
    2023-01-03: PMD [None]
    2023-01-06: Food waste [None]
    2023-01-06: Pruning waste [None]
    2023-01-06: Green waste [None]
    2023-01-06: Household waste [None]
    2023-01-06: Paper-cardboard [None]
    2023-01-10: Household waste [None]
    2023-01-10: PMD [None]
    2023-01-13: Food waste [None]
    2023-01-13: Pruning waste [None]
    2023-01-13: Green waste [None]
    2023-01-13: Household waste [None]
    2023-01-13: Paper-cardboard [None]
    2023-01-17: Household waste [None]
    2023-01-17: PMD [None]
    2023-01-20: Food waste [None]
    2023-01-20: Pruning waste [None]
    2023-01-20: Green waste [None]
    2023-01-20: Household waste [None]
    2023-01-20: Paper-cardboard [None]
    2023-01-24: Household waste [None]
    2023-01-24: PMD [None]
    2023-01-27: Food waste [None]
    2023-01-27: Pruning waste [None]
    2023-01-27: Green waste [None]
    2023-01-27: Household waste [None]
    2023-01-27: Paper-cardboard [None]
    2023-01-31: Household waste [None]
    2023-01-31: PMD [None]
    2023-02-03: Food waste [None]
    2023-02-03: Pruning waste [None]
    2023-02-03: Green waste [None]
    2023-02-03: Household waste [None]
    2023-02-03: Paper-cardboard [None]
    2023-02-07: Household waste [None]
    2023-02-07: PMD [None]
    2023-02-10: Food waste [None]
    2023-02-10: Pruning waste [None]
    2023-02-10: Green waste [None]
    2023-02-10: Household waste [None]
    2023-02-10: Paper-cardboard [None]
    2023-02-14: Household waste [None]
    2023-02-14: PMD [None]
    2023-02-17: Food waste [None]
    2023-02-17: Pruning waste [None]
    2023-02-17: Green waste [None]
    2023-02-17: Household waste [None]
    2023-02-17: Paper-cardboard [None]
    2023-02-21: Household waste [None]
    2023-02-21: PMD [None]
    2023-02-24: Food waste [None]
    2023-02-24: Pruning waste [None]
    2023-02-24: Green waste [None]
    2023-02-24: Household waste [None]
    2023-02-24: Paper-cardboard [None]
    2023-02-28: Household waste [None]
    2023-02-28: PMD [None]
    2023-03-03: Food waste [None]
    2023-03-03: Pruning waste [None]
    2023-03-03: Green waste [None]
    2023-03-03: Household waste [None]
    2023-03-03: Paper-cardboard [None]
    2023-03-07: Household waste [None]
    2023-03-07: PMD [None]
    2023-03-10: Food waste [None]
    2023-03-10: Pruning waste [None]
    2023-03-10: Green waste [None]
    2023-03-10: Household waste [None]
    2023-03-10: Paper-cardboard [None]
    2023-03-14: Household waste [None]
    2023-03-14: PMD [None]
    2023-03-17: Food waste [None]
    2023-03-17: Pruning waste [None]
    2023-03-17: Green waste [None]
    2023-03-17: Household waste [None]
    2023-03-17: Paper-cardboard [None]
    2023-03-21: Household waste [None]
    2023-03-21: PMD [None]
    2023-03-24: Food waste [None]
    2023-03-24: Pruning waste [None]
    2023-03-24: Green waste [None]
    2023-03-24: Household waste [None]
    2023-03-24: Paper-cardboard [None]
    2023-03-28: Household waste [None]
    2023-03-28: PMD [None]
    2023-03-31: Food waste [None]
    2023-03-31: Pruning waste [None]
    2023-03-31: Green waste [None]
    2023-03-31: Household waste [None]
    2023-03-31: Paper-cardboard [None]
    2023-04-04: Household waste [None]
    2023-04-04: PMD [None]
    2023-04-07: Food waste [None]
    2023-04-07: Pruning waste [None]
    2023-04-07: Green waste [None]
    2023-04-07: Household waste [None]
    2023-04-07: Paper-cardboard [None]
    2023-04-11: Household waste [None]
    2023-04-11: PMD [None]
    2023-04-14: Food waste [None]
    2023-04-14: Pruning waste [None]
    2023-04-14: Green waste [None]
    2023-04-14: Household waste [None]
    2023-04-14: Paper-cardboard [None]
    2023-04-18: Household waste [None]
    2023-04-18: PMD [None]
    2023-04-21: Food waste [None]
    2023-04-21: Pruning waste [None]
    2023-04-21: Green waste [None]
    2023-04-21: Household waste [None]
    2023-04-21: Paper-cardboard [None]
    2023-04-25: Household waste [None]
    2023-04-25: PMD [None]
    2023-04-28: Food waste [None]
    2023-04-28: Pruning waste [None]
    2023-04-28: Green waste [None]
    2023-04-28: Household waste [None]
    2023-04-28: Paper-cardboard [None]
    2023-05-02: Household waste [None]
    2023-05-02: PMD [None]
    2023-05-05: Food waste [None]
    2023-05-05: Pruning waste [None]
    2023-05-05: Green waste [None]
    2023-05-05: Household waste [None]
    2023-05-05: Paper-cardboard [None]
    2023-05-09: Household waste [None]
    2023-05-09: PMD [None]
    2023-05-12: Food waste [None]
    2023-05-12: Pruning waste [None]
    2023-05-12: Green waste [None]
    2023-05-12: Household waste [None]
    2023-05-12: Paper-cardboard [None]
    2023-05-16: Household waste [None]
    2023-05-16: PMD [None]
    2023-05-19: Food waste [None]
    2023-05-19: Pruning waste [None]
    2023-05-19: Green waste [None]
    2023-05-19: Household waste [None]
    2023-05-19: Paper-cardboard [None]
    2023-05-23: Household waste [None]
    2023-05-23: PMD [None]
    2023-05-26: Food waste [None]
    2023-05-26: Pruning waste [None]
    2023-05-26: Green waste [None]
    2023-05-26: Household waste [None]
    2023-05-26: Paper-cardboard [None]
    2023-05-30: Household waste [None]
    2023-05-30: PMD [None]
    2023-06-02: Food waste [None]
    2023-06-02: Pruning waste [None]
    2023-06-02: Green waste [None]
    2023-06-02: Household waste [None]
    2023-06-02: Paper-cardboard [None]
    2023-06-06: Household waste [None]
    2023-06-06: PMD [None]
    2023-06-09: Food waste [None]
    2023-06-09: Pruning waste [None]
    2023-06-09: Green waste [None]
    2023-06-09: Household waste [None]
    2023-06-09: Paper-cardboard [None]
    2023-06-13: Household waste [None]
    2023-06-13: PMD [None]
    2023-06-16: Food waste [None]
    2023-06-16: Pruning waste [None]
    2023-06-16: Green waste [None]
    2023-06-16: Household waste [None]
    2023-06-16: Paper-cardboard [None]
    2023-06-20: Household waste [None]
    2023-06-20: PMD [None]
    2023-06-23: Food waste [None]
    2023-06-23: Pruning waste [None]
    2023-06-23: Green waste [None]
    2023-06-23: Household waste [None]
    2023-06-23: Paper-cardboard [None]
    2023-06-27: Household waste [None]
    2023-06-27: PMD [None]
    2023-06-30: Food waste [None]
    2023-06-30: Pruning waste [None]
    2023-06-30: Green waste [None]
    2023-06-30: Household waste [None]
    2023-06-30: Paper-cardboard [None]
    2023-07-04: Household waste [None]
    2023-07-04: PMD [None]
    2023-07-07: Food waste [None]
    2023-07-07: Pruning waste [None]
    2023-07-07: Green waste [None]
    2023-07-07: Household waste [None]
    2023-07-07: Paper-cardboard [None]
    2023-07-11: Household waste [None]
    2023-07-11: PMD [None]
    2023-07-14: Food waste [None]
    2023-07-14: Pruning waste [None]
    2023-07-14: Green waste [None]
    2023-07-14: Household waste [None]
    2023-07-14: Paper-cardboard [None]
    2023-07-18: Household waste [None]
    2023-07-18: PMD [None]
    2023-07-21: Food waste [None]
    2023-07-21: Pruning waste [None]
    2023-07-21: Green waste [None]
    2023-07-21: Household waste [None]
    2023-07-21: Paper-cardboard [None]
    2023-07-25: Household waste [None]
    2023-07-25: PMD [None]
    2023-07-28: Food waste [None]
    2023-07-28: Pruning waste [None]
    2023-07-28: Green waste [None]
    2023-07-28: Household waste [None]
    2023-07-28: Paper-cardboard [None]
    2023-08-01: Household waste [None]
    2023-08-01: PMD [None]
    2023-08-04: Food waste [None]
    2023-08-04: Pruning waste [None]
    2023-08-04: Green waste [None]
    2023-08-04: Household waste [None]
    2023-08-04: Paper-cardboard [None]
    2023-08-08: Household waste [None]
    2023-08-08: PMD [None]
    2023-08-11: Food waste [None]
    2023-08-11: Pruning waste [None]
    2023-08-11: Green waste [None]
    2023-08-11: Household waste [None]
    2023-08-11: Paper-cardboard [None]
    2023-08-15: Household waste [None]
    2023-08-15: PMD [None]
    2023-08-18: Food waste [None]
    2023-08-18: Pruning waste [None]
    2023-08-18: Green waste [None]
    2023-08-18: Household waste [None]
    2023-08-18: Paper-cardboard [None]
    2023-08-22: Household waste [None]
    2023-08-22: PMD [None]
    2023-08-25: Food waste [None]
    2023-08-25: Pruning waste [None]
    2023-08-25: Green waste [None]
    2023-08-25: Household waste [None]
    2023-08-25: Paper-cardboard [None]
    2023-08-29: Household waste [None]
    2023-08-29: PMD [None]
    2023-09-01: Food waste [None]
    2023-09-01: Pruning waste [None]
    2023-09-01: Green waste [None]
    2023-09-01: Household waste [None]
    2023-09-01: Paper-cardboard [None]
    2023-09-05: Household waste [None]
    2023-09-05: PMD [None]
    2023-09-08: Food waste [None]
    2023-09-08: Pruning waste [None]
    2023-09-08: Green waste [None]
    2023-09-08: Household waste [None]
    2023-09-08: Paper-cardboard [None]
    2023-09-12: Household waste [None]
    2023-09-12: PMD [None]
    2023-09-15: Food waste [None]
    2023-09-15: Pruning waste [None]
    2023-09-15: Green waste [None]
    2023-09-15: Household waste [None]
    2023-09-15: Paper-cardboard [None]
    2023-09-19: Household waste [None]
    2023-09-19: PMD [None]
    2023-09-22: Food waste [None]
    2023-09-22: Pruning waste [None]
    2023-09-22: Green waste [None]
    2023-09-22: Household waste [None]
    2023-09-22: Paper-cardboard [None]
    2023-09-26: Household waste [None]
    2023-09-26: PMD [None]
    2023-09-29: Food waste [None]
    2023-09-29: Pruning waste [None]
    2023-09-29: Green waste [None]
    2023-09-29: Household waste [None]
    2023-09-29: Paper-cardboard [None]
    2023-10-03: Household waste [None]
    2023-10-03: PMD [None]
    2023-10-06: Food waste [None]
    2023-10-06: Pruning waste [None]
    2023-10-06: Green waste [None]
    2023-10-06: Household waste [None]
    2023-10-06: Paper-cardboard [None]
    2023-10-10: Household waste [None]
    2023-10-10: PMD [None]
    2023-10-13: Food waste [None]
    2023-10-13: Pruning waste [None]
    2023-10-13: Green waste [None]
    2023-10-13: Household waste [None]
    2023-10-13: Paper-cardboard [None]
    2023-10-17: Household waste [None]
    2023-10-17: PMD [None]
    2023-10-20: Food waste [None]
    2023-10-20: Pruning waste [None]
    2023-10-20: Green waste [None]
    2023-10-20: Household waste [None]
    2023-10-20: Paper-cardboard [None]
    2023-10-24: Household waste [None]
    2023-10-24: PMD [None]
  found 19 entries for 3001, Waversebaan 276 with events
    2022-10-25: Paper-cardboard [None]
    2022-10-31: Gft [None]
    2022-10-31: PMD [None]
    2022-11-07: Huisvuil [None]
    2022-11-12: Repair Café [None]
    2022-11-14: Gft [None]
    2022-11-14: PMD [None]
    2022-11-19: Repair Café [None]
    2022-11-21: Huisvuil [None]
    2022-11-22: Paper-cardboard [None]
    2022-11-28: Gft [None]
    2022-11-28: PMD [None]
    2022-12-05: Huisvuil [None]
    2022-12-08: Repair Café [None]
    2022-12-10: Repair Café [None]
    2022-12-12: Gft [None]
    2022-12-12: PMD [None]
    2022-12-17: Repair Café [None]
    2022-12-19: Huisvuil [None]
  found 14 entries for 3001, Waversebaan 276 without events
    2022-10-25: Paper-cardboard [None]
    2022-10-31: Gft [None]
    2022-10-31: PMD [None]
    2022-11-07: Huisvuil [None]
    2022-11-14: Gft [None]
    2022-11-14: PMD [None]
    2022-11-21: Huisvuil [None]
    2022-11-22: Paper-cardboard [None]
    2022-11-28: Gft [None]
    2022-11-28: PMD [None]
    2022-12-05: Huisvuil [None]
    2022-12-12: Gft [None]
    2022-12-12: PMD [None]
    2022-12-19: Huisvuil [None]
  found 20 entries for 1400, Rue de namur 1 with events
    2022-10-27: Organic waste [None]
    2022-10-27: Residual household waste [None]
    2022-10-28: PMD [None]
    2022-11-03: Organic waste [None]
    2022-11-03: Residual household waste [None]
    2022-11-10: Organic waste [None]
    2022-11-10: Residual household waste [None]
    2022-11-12: PMD [None]
    2022-11-17: Organic waste [None]
    2022-11-17: Residual household waste [None]
    2022-11-18: Paper-cardboard [None]
    2022-11-24: Organic waste [None]
    2022-11-24: Residual household waste [None]
    2022-11-25: PMD [None]
    2022-12-01: Organic waste [None]
    2022-12-01: Residual household waste [None]
    2022-12-08: Organic waste [None]
    2022-12-08: Residual household waste [None]
    2022-12-09: PMD [None]
    2022-12-15: Organic waste [None]

```
