### ISSUE TITLE
How do I figure out why the collection is failing?

### ISSUE THREAD

**Issue by NZRobNZ** [mampfes/hacs_waste_collection_schedule#423]
I'm getting the following from the waste_collection_schedule.scraper - it appears to not like the way things are getting requested? "Max retries exceeded with url..."
Note, this is NOT for my address, I'm using the sample code for now until I can get the thing working...
```
This error originated from a custom integration.

Logger: waste_collection_schedule.scraper
Source: custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py:143
Integration: waste_collection_schedule (documentation)
First occurred: 5:10:11 PM (1 occurrences)
Last logged: 5:10:11 PM

fetch failed for source Auckland council: Traceback (most recent call last): File "/srv/homeassistant/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "/srv/homeassistant/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request self._validate_conn(conn) File "/srv/homeassistant/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn conn.connect() File "/srv/homeassistant/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect self.sock = ssl_wrap_socket( File "/srv/homeassistant/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket ssl_sock = _ssl_wrap_socket_impl( File "/srv/homeassistant/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl return ssl_context.wrap_socket(sock, server_hostname=server_hostname) File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket return self.sslsocket_class._create( File "/usr/lib/python3.10/ssl.py", line 1071, in _create self.do_handshake() File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake self._sslobj.do_handshake() ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/srv/homeassistant/lib/python3.10/site-packages/requests/adapters.py", line 489, in send resp = conn.urlopen( File "/srv/homeassistant/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen retries = retries.increment( File "/srv/homeassistant/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.aucklandcouncil.govt.nz', port=443): Max retries exceeded with url: /rubbish-recycling/rubbish-recycling-collections/Pages/collection-day-detail.aspx?an=112342306525 (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)'))) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/home/homeassistant/.homeassistant/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", line 141, in fetch entries = self._source.fetch() File "/home/homeassistant/.homeassistant/custom_components/waste_collection_schedule/waste_collection_schedule/source/aucklandcouncil_govt_nz.py", line 111, in fetch r = requests.get( File "/srv/homeassistant/lib/python3.10/site-packages/requests/api.py", line 73, in get return request("get", url, params=params, **kwargs) File "/srv/homeassistant/lib/python3.10/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "/srv/homeassistant/lib/python3.10/site-packages/requests/sessions.py", line 587, in request resp = self.send(prep, **send_kwargs) File "/srv/homeassistant/lib/python3.10/site-packages/requests/sessions.py", line 701, in send r = adapter.send(request, **kwargs) File "/srv/homeassistant/lib/python3.10/site-packages/requests/adapters.py", line 563, in send raise SSLError(e, request=request) requests.exceptions.SSLError: HTTPSConnectionPool(host='www.aucklandcouncil.govt.nz', port=443): Max retries exceeded with url: /rubbish-recycling/rubbish-recycling-collections/Pages/collection-day-detail.aspx?an=112342306525 (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)')))
```

**Comment by dt215git** [comment]
A quick google of that SSL error message revealed [this discussion on StackOverflow](https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled). A few possible solutions are discussed. Having had a quick play, the code snippet in the last message appears to provide a workaround.

```$ python3 test_sources.py -s aucklandcouncil_govt_nz -l -i
Testing source aucklandcouncil_govt_nz ...
  found 3 entries for 429 Sea View Road
    2022-11-14: rubbish [None]
    2022-11-14: recycle [None]
    2022-11-21: rubbish [None]
  found 3 entries for 8 Dickson Road
    2022-11-10: rubbish [None]
    2022-11-17: rubbish [None]
    2022-11-17: recycle [None]
```
I'll tidy it up a bit and create a PR, but the best solution seems to be for Auckland Council to update their server.
