### ISSUE TITLE
Error during setup of component with 1.32.0

### ISSUE THREAD

**Issue by kgroshert** [mampfes/hacs_waste_collection_schedule#558]
Version: 1.31.0 -> 1.32.0
HA Version: 2022.12.9

Just upgraded to 1.32.0 via HACS but getting this error after restart of HA. Downgraded to 1.31.0 and it works again.

```
Logger: homeassistant.setup
Source: util/package.py:40
First occurred: 22:29:10 (1 occurrences)
Last logged: 22:29:10

Error during setup of component waste_collection_schedule
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3037, in _dep_map
    return self.__dep_map
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2834, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3028, in _parsed_pkg_info
    return self._pkg_info
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2834, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 120, in async_setup
    await hass.helpers.discovery.async_load_platform(
  File "/usr/src/homeassistant/homeassistant/helpers/discovery.py", line 156, in async_load_platform
    setup_success = await setup.async_setup_component(hass, component, hass_config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 97, in async_setup_component
    return await task
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    processed_config = await conf_util.async_process_component_config(
  File "/usr/src/homeassistant/homeassistant/config.py", line 917, in async_process_component_config
    p_integration = await async_get_integration_with_requirements(hass, p_name)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 51, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 185, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 251, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 276, in _async_process_requirements
    installed, failures = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 112, in _install_requirements_if_missing
    if pkg_util.is_installed(req) or _install_with_retry(req, kwargs):
  File "/usr/src/homeassistant/homeassistant/util/package.py", line 40, in is_installed
    pkg_resources.get_distribution(package)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 478, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 354, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 803, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2755, in requires
    dm = self._dep_map
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3039, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3048, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3030, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1431, in get_metadata
    value = self._get(path)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1635, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/site-packages/pytz-2022.7.dist-info/METADATA'

```

**Comment by mampfes** [comment]
Hm, sounds like an problem during installation of the requirements. Waste Collection Schedule is not involved during this stage, therefore there is not much we can do.
Please try to reinstall or check the discussion in #220

**Comment by kgroshert** [comment]
Damn. Reinstalling fixed it. I hate it when IT does that 😄
Thanks a lot, will close the issue.

**Comment by kgroshert** [comment]
Reopening because the error was back with the next HA upgrade:

Upgraded to 2023.0 -> hacs_waste_collection_schedule broken again
Reinstalled hacs_waste_collection_schedule -> everything works
Upgraded to 2023.1 -> hacs_waste_collection_schedule broken again
Reinstalled hacs_waste_collection_schedule -> everything works

Not sure how https://github.com/mampfes/hacs_waste_collection_schedule/issues/220 applies here. Anything I can check? I'm on standard Home Assistant install (aka hass.io).

**Comment by mampfes** [comment]
Hm, strange. But again - the integration has nothing to do with the upgrade or installation of required packages. Therefore there is not much we can do here.

**Comment by troed** [comment]
I have this as well. The issue is that pytz 2022.7 gets installed but icalevents needs no newer 2021.3.

# icalevents 0.1.27 requires pytz<2022.0,>=2021.3

(and yeah, 0.1.27 is the newest icalevents)

Manually downgrading pytz works.
