### ISSUE TITLE
ICS fetch failed: KeyError DTSTART

### ISSUE THREAD

**Issue by crixionz** [mampfes/hacs_waste_collection_schedule#633]
Hi!
I get this error 
```yaml
2023-01-20 14:58:57.739 ERROR (SyncWorker_1) [waste_collection_schedule.source_shell] fetch failed for source ICS:
Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch
    entries = self._source.fetch()
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 185, in fetch
    return self.fetch_url(self._url, self._params)
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 206, in fetch_url
    return self._convert(r.text)
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 217, in _convert
    dates = self._ics.convert(data)
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 38, in convert
    events: List[Any] = icalevents.events(
  File "/usr/local/lib/python3.10/site-packages/icalevents/icalevents.py", line 57, in events
    found_events += parse_events(
  File "/usr/local/lib/python3.10/site-packages/icalevents/icalparser.py", line 306, in parse_events
    timezones[name] = c.to_tz()
  File "/usr/local/lib/python3.10/site-packages/icalendar/cal.py", line 601, in to_tz
    assert isinstance(component['DTSTART'].dt, datetime), (
  File "/usr/local/lib/python3.10/site-packages/icalendar/caselessdict.py", line 42, in __getitem__
    return super(CaselessDict, self).__getitem__(key.upper())
KeyError: 'DTSTART'
```
for the following configuration
```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://service.stuttgart.de/lhs-services/aws/api/ical?street=Kelterstr.&streetnr=20
      calendar_title: waste
```
In that ICS file, `DTSTART` follows this pattern `DTSTART;TZID=Europe/Berlin:20230124T063000`

This configuration worked fine a few weeks ago, I didn't change it since.

I'm on the newest version 1.34.0 and HA version 2023.01.4. 
Let me know if you need more info on this :)

**Comment by dt215git** [comment]
There are two ways of processing ics files and they seem to manage dates differently. From the [iCal/ICS](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) page:
![image](https://user-images.githubusercontent.com/86194065/213859963-f817674c-faba-4f5e-848e-78ca4fc4f203.png)

Try this:
```yaml
  sources:
    - name: ics
      calendar_title: Test_Waste
      args:
        url: https://service.stuttgart.de/lhs-services/aws/api/ical?street=Kelterstr.&streetnr=20
        version: 1
```
![image](https://user-images.githubusercontent.com/86194065/213859829-9f9358a6-f55e-4482-a2a4-14dda72b7838.png)
![image](https://user-images.githubusercontent.com/86194065/213859872-0afdfebc-0c61-46c6-a962-e8245978ba50.png)

**Comment by mampfes** [comment]
Or try the [stuttgart_de](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/stuttgart_de.md) source.

**Comment by crixionz** [comment]
Thank you all! 💪❤️
