### ISSUE TITLE
Setup failed for custom integration waste_collection_schedule:

### ISSUE THREAD

**Issue by marcinwrobel** [mampfes/hacs_waste_collection_schedule#732]
After updating HA to version 2023.3, I get integration errors.
Hacs version: 1.31.0
Waste Collection Schedule version: 1.36.0
LOG:
Logger: homeassistant.setup
Source: setup.py:213
First occurred: 16:56:51 (1 occurrences)
Last logged: 16:56:51

Setup failed for custom integration waste_collection_schedule: Unable to import component: No module named 'waste_collection_schedule.source_shell'

LOG:

Ten błąd pochodzi z niestandardowej integracji.

Logger: homeassistant.config
Source: custom_components/waste_collection_schedule/waste_collection_schedule/__init__.py:3
Integration: waste_collection_schedule (documentation)
First occurred: 16:56:51 (6 occurrences)
Last logged: 16:56:51

Platform error: sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 928, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 21, in <module>
    from waste_collection_schedule import Customize, SourceShell  # type: ignore # isort:skip # noqa: E402
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/__init__.py", line 3, in <module>
    from .source_shell import Customize, SourceShell  # noqa: F401
ModuleNotFoundError: No module named 'waste_collection_schedule.source_shell'

**Comment by mampfes** [comment]
Please try to reinstall it. Home Assistant (or HACS) sometimes doesn't install all required files.

**Comment by marcinwrobel** [comment]
Thank you, it works.
