### ISSUE TITLE
Test script seems broken 

### ISSUE THREAD

**Issue by kanthamohan** [mampfes/hacs_waste_collection_schedule#838]
The test_sources.py script seems broken.  When trying to test a new source integration that I created for chiltern.gov.uk it seems to throw the following in 

Testing source chiltern_gov_uk.py ...
Traceback (most recent call last):
  File "./test_sources.py", line 161, in <module>
    main()
  File "./test_sources.py", line 67, in main
    module = importlib.import_module(f"waste_collection_schedule.source.{f}")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'waste_collection_schedule.source.chiltern_gov_uk.py'; 'waste_collection_schedule.source.chiltern_gov_uk' is not a package

Also the update_docu_links.py seems to throw an error with many of the scripts and never seem to run, despite my various attempts to get past each of them.   Am I missing something?

**Comment by 5ila5** [comment]
looks like you ran `./test_sources.py -s chiltern_gov_uk.py` but you have to use `./test_sources.py -s chiltern_gov_uk` (see [contributing guide](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/contributing.md#test-the-new-source-file))
the update_docu_links.py seems to work correct on my side, can you post your error messages?

**Comment by kanthamohan** [comment]
Aha!!! it was always going to be something silly on my part. Thanks for point out. the Tests run OK now. 

Any pointers on update_docu_links.py ?

**Comment by 5ila5** [comment]
seems to work can you provide any error messages?

**Comment by kanthamohan** [comment]
kanth@macbookpro hacs_waste_collection_schedule % ./update_docu_links.py 
/Users/kanth/Desktop/hacs_waste_collection_schedule/custom_components/waste_collection_schedule/waste_collection_schedule/source
Traceback (most recent call last):
  File "./update_docu_links.py", line 305, in <module>
    main()
  File "./update_docu_links.py", line 62, in main
    module = importlib.import_module(f"waste_collection_schedule.source.{f}")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/kanth/Desktop/hacs_waste_collection_schedule/custom_components/waste_collection_schedule/waste_collection_schedule/source/rotherham_gov_uk.py", line 21, in <module>
    "Black bin": "mdi:recycle",
TypeError: 'type' object is not subscriptable


This is what I get when I run it...

**Comment by 5ila5** [comment]
this probably happens because rotherham_gov_uk (and maybe some more) use type hinting for dictionaries which is not supported by python versions below 3.9 and you seem to use 3.7 this is probably causing this exception.
Homeassistant requires Python >=3.10.0 so it's not a problem using this extension.
python3.7 reached end of life at 2023-06-27. so It's probably best to update your python version.

**Comment by kanthamohan** [comment]
Thanks, that fixed it.
