### ISSUE TITLE
Source Error: UK, Vale of Whitehorse/South Oxfordshire

### ISSUE THREAD

**Issue by sembeeuk** [mampfes/hacs_waste_collection_schedule#937]
With the public holiday here in the UK this week, the bin collection days have changed. 
The Binzone source appears to be sending additional text which is breaking the content. 
Full error from the HA logs below:

`fetch failed for source Binzone: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/binzone_uk.py", line 90, in fetch date=parse(bin_date).date(), File "/usr/local/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 1368, in parse return DEFAULTPARSER.parse(timestr, **kwargs) File "/usr/local/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 643, in parse raise ParserError("Unknown string format: %s", timestr) dateutil.parser._parser.ParserError: Unknown string format: Your usual collection day is different this weekThursday 4 May`

**Comment by dt215git** [comment]
A quick-fix is the following, but it will fail if they decide to use different text  at some point.

```python
bin_date = bin_info[0].strip().replace("Your usual collection day is different this week", "")
bin_type = bin_info[1].strip().replace("Your usual collection day is different this week", "")
```

```bash
Testing source binzone_uk ...
  found 7 entries for VOWH
    2023-05-06 : GREY BIN [mdi:trash-can]
    2023-05-06 : SMALL ELECTRICAL ITEMS [mdi:hair-dryer]
    2023-05-06 : FOOD BIN [mdi:food-apple]
    2023-05-13 : GREEN BIN [mdi:recycle]
    2023-05-13 : GARDEN WASTE [mdi:leaf]
    2023-05-13 : FOOD BIN [mdi:food-apple]
    2023-05-13 : TEXTILES [mdi:hanger]
  found 7 entries for SO
    2023-05-05 : GREEN BIN [mdi:recycle]
    2023-05-05 : GARDEN WASTE [mdi:leaf]
    2023-05-05 : FOOD BIN [mdi:food-apple]
    2023-05-05 : TEXTILES [mdi:hanger]
    2023-05-12 : GREY BIN [mdi:trash-can]
    2023-05-12 : SMALL ELECTRICAL ITEMS [mdi:hair-dryer]
    2023-05-12 : FOOD BIN [mdi:food-apple]
```

**Comment by 5ila5** [comment]
fixed by #938
