### ISSUE TITLE
Error when initializing component.

### ISSUE THREAD

**Issue by schale01** [mampfes/hacs_waste_collection_schedule#968]
This error originated from a custom integration.

```
Logger: homeassistant.setup
Source: [custom_components/waste_collection_schedule/waste_collection_schedule/source/static.py:95](http://custom_components/waste_collection_schedule/waste_collection_schedule/source/static.py:95)
Integration: waste_collection_schedule (documentation)
First occurred: 10:38:52 PM (1 occurrences)
Last logged: 10:38:52 PM

Error during setup of component waste_collection_schedule
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 257, in _async_setup_component
    result = await task
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 109, in async_setup
    api.add_source_shell(
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 202, in add_source_shell
    SourceShell.create(
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 196, in create
    source = source_module.Source(**source_args)  # type: ignore
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/static.py", line 95, in __init__
    self._start = parser.isoparse(start).date() if start else None
  File "/usr/local/lib/python3.10/site-packages/dateutil/parser/isoparser.py", line 37, in func
    return f(self, str_in, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dateutil/parser/isoparser.py", line 134, in isoparse
    components, pos = self._parse_isodate(dt_str)
  File "/usr/local/lib/python3.10/site-packages/dateutil/parser/isoparser.py", line 208, in _parse_isodate
    return self._parse_isodate_common(dt_str)
  File "/usr/local/lib/python3.10/site-packages/dateutil/parser/isoparser.py", line 213, in _parse_isodate_common
    len_str = len(dt_str)
TypeError: object of type 'datetime.date' has no len()
```

**Comment by schale01** [comment]
FIXED!

Issue was that the start date would not pass correctly without  being in quote. 
May want to update the documentation as the examples for static show without quotes. 


#Waste Collection Schedule
waste_collection_schedule:
  sources:
    - name: static
      args: 
        type: Trash
        frequency: WEEKLY
        weekdays: FR
    - name: static 
      args: 
        type: Recycle
        frequency: WEEKLY
        interval: 2
        start: '2023-05-12' 
    - name: static
      args:
        type: Yard Waste
        frequency: WEEKLY
        interval: 2
        start: '2023-05-19'
